{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default (printf "%s-cert" (include "postbrain.fullname" .)) .Values.certificate.name }}
  labels:
    {{- include "postbrain.labels" . | nindent 4 }}
    {{- with .Values.certificate.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  secretName: {{ .Values.certificate.secretName | quote }}
  privateKey:
    rotationPolicy: {{ .Values.certificate.privateKey.rotationPolicy }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name | quote }}
    kind: {{ .Values.certificate.issuerRef.kind | quote }}
    group: {{ .Values.certificate.issuerRef.group | quote }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
