apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postbrain.fullname" . }}-config
  labels:
    {{- include "postbrain.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ include "postbrain.config" . | indent 4 }}
