DROP TABLE IF EXISTS {{POSTBRAIN_SCHEMA}}.oauth_auth_codes;
DROP TABLE IF EXISTS {{POSTBRAIN_SCHEMA}}.social_identities;
DROP TABLE IF EXISTS {{POSTBRAIN_SCHEMA}}.oauth_clients;
DROP TABLE IF EXISTS {{POSTBRAIN_SCHEMA}}.oauth_states;
