DROP INDEX IF EXISTS {{POSTBRAIN_SCHEMA}}.relations_source_file_idx;
ALTER TABLE {{POSTBRAIN_SCHEMA}}.relations DROP COLUMN IF EXISTS source_file;
ALTER TABLE {{POSTBRAIN_SCHEMA}}.scopes DROP COLUMN IF EXISTS last_indexed_commit;
ALTER TABLE {{POSTBRAIN_SCHEMA}}.scopes DROP COLUMN IF EXISTS repo_default_branch;
ALTER TABLE {{POSTBRAIN_SCHEMA}}.scopes DROP COLUMN IF EXISTS repo_url;
