// Package ui provides the HTTP handler for the Postbrain Web UI.
package ui

import (
	"embed"
	"html/template"
	"io/fs"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/simplyblock/postbrain/internal/db"
)

//go:embed web/templates
var templatesFS embed.FS

//go:embed web/static
var staticFS embed.FS

// Handler holds all dependencies for the UI.
type Handler struct {
	pool      *pgxpool.Pool
	templates *template.Template
	staticFS  fs.FS
}

// NewHandler creates a UI Handler with parsed templates.
func NewHandler(pool *pgxpool.Pool) (*Handler, error) {
	funcMap := template.FuncMap{
		"truncate":    truncate,
		"timeAgo":     timeAgo,
		"deref":       derefString,
		"derefTime":   derefTime,
		"statusBadge": statusBadge,
		"join":        strings.Join,
	}
	tmpl, err := template.New("").Funcs(funcMap).ParseFS(templatesFS, "web/templates/*.html")
	if err != nil {
		return nil, err
	}
	sub, err := fs.Sub(staticFS, "web/static")
	if err != nil {
		return nil, err
	}
	return &Handler{pool: pool, templates: tmpl, staticFS: sub}, nil
}

// ServeHTTP routes /ui/* requests.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// Serve static files.
	if strings.HasPrefix(r.URL.Path, "/ui/static/") {
		http.StripPrefix("/ui/static/", http.FileServer(http.FS(h.staticFS))).ServeHTTP(w, r)
		return
	}
	// Login form and POST.
	if r.URL.Path == "/ui/login" {
		h.handleLogin(w, r)
		return
	}
	// Auth check for all other routes.
	if !h.authenticated(w, r) {
		return
	}
	switch {
	case r.URL.Path == "/ui" || r.URL.Path == "/ui/":
		h.handleOverview(w, r)
	case r.URL.Path == "/ui/memories":
		h.handleMemories(w, r)
	case strings.HasPrefix(r.URL.Path, "/ui/memories/"):
		h.handleMemoryDetail(w, r)
	case r.URL.Path == "/ui/knowledge":
		h.handleKnowledge(w, r)
	case strings.HasPrefix(r.URL.Path, "/ui/knowledge/"):
		h.handleKnowledgeDetail(w, r)
	case r.URL.Path == "/ui/collections":
		h.handleCollections(w, r)
	case r.URL.Path == "/ui/promotions":
		h.handlePromotions(w, r)
	case r.URL.Path == "/ui/staleness":
		h.handleStaleness(w, r)
	case r.URL.Path == "/ui/graph":
		h.handleGraph(w, r)
	case r.URL.Path == "/ui/skills":
		h.handleSkills(w, r)
	case r.URL.Path == "/ui/principals":
		h.handlePrincipals(w, r)
	case r.URL.Path == "/ui/scopes" && r.Method == http.MethodPost:
		h.handleCreateScope(w, r)
	case r.URL.Path == "/ui/metrics":
		h.handleMetrics(w, r)
	default:
		http.NotFound(w, r)
	}
}

// render renders a named template wrapped in the base layout.
// For HTMX requests (HX-Request: true header), renders only the content template.
func (h *Handler) render(w http.ResponseWriter, r *http.Request, tmplName string, title string, data any) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if r.Header.Get("HX-Request") == "true" {
		if err := h.templates.ExecuteTemplate(w, tmplName, data); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}
	// Render content to buffer first, then wrap in base layout.
	var buf strings.Builder
	if err := h.templates.ExecuteTemplate(&buf, tmplName, data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if err := h.templates.ExecuteTemplate(w, "base", struct {
		Title   string
		Content template.HTML
	}{
		Title:   title,
		Content: template.HTML(buf.String()), //nolint:gosec // generated by our own templates
	}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// handleOverview serves GET /ui — server health and schema version.
func (h *Handler) handleOverview(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Status          string
		SchemaVersion   uint
		ExpectedVersion uint
		SchemaDirty     bool
	}{
		Status:          "ok",
		SchemaVersion:   0,
		ExpectedVersion: 0,
		SchemaDirty:     false,
	}
	if h.pool != nil {
		sv, dirty, err := db.SchemaVersion(r.Context(), h.pool)
		if err == nil {
			data.SchemaVersion = sv
			data.SchemaDirty = dirty
		} else {
			data.Status = "degraded"
		}
	}
	h.render(w, r, "health", "Overview", data)
}

// handleMemories serves GET /ui/memories.
func (h *Handler) handleMemories(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	scopeID := r.URL.Query().Get("scope_id")

	data := struct {
		Query      string
		ScopeID    string
		Memories   []*db.Memory
		NextCursor string
	}{
		Query:    q,
		ScopeID:  scopeID,
		Memories: nil,
	}

	if h.pool != nil && scopeID != "" {
		sid, err := uuid.Parse(scopeID)
		if err == nil {
			mems, err := db.ListMemoriesByScope(r.Context(), h.pool, sid, 20, 0)
			if err == nil {
				data.Memories = mems
			}
		}
	}

	tmpl := "memories"
	if r.Header.Get("HX-Request") == "true" {
		tmpl = "memories_rows"
	}
	h.render(w, r, tmpl, "Memories", data)
}

// handleMemoryDetail serves GET /ui/memories/{id}.
func (h *Handler) handleMemoryDetail(w http.ResponseWriter, r *http.Request) {
	idStr := strings.TrimPrefix(r.URL.Path, "/ui/memories/")
	id, err := uuid.Parse(idStr)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	data := struct {
		Memory *db.Memory
	}{}

	if h.pool != nil {
		mem, err := db.GetMemory(r.Context(), h.pool, id)
		if err != nil || mem == nil {
			http.NotFound(w, r)
			return
		}
		data.Memory = mem
	}

	h.render(w, r, "memory_detail", "Memory", data)
}

// handleKnowledge serves GET /ui/knowledge.
func (h *Handler) handleKnowledge(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	_ = q

	data := struct {
		Query     string
		Artifacts []*db.KnowledgeArtifact
	}{
		Query:     q,
		Artifacts: nil,
	}

	if h.pool != nil {
		arts, err := db.ListVisibleArtifacts(r.Context(), h.pool, nil, 20, 0)
		if err == nil {
			data.Artifacts = arts
		}
	}

	tmpl := "knowledge"
	if r.Header.Get("HX-Request") == "true" {
		tmpl = "knowledge_rows"
	}
	h.render(w, r, tmpl, "Knowledge", data)
}

// handleKnowledgeDetail serves GET /ui/knowledge/{id}.
func (h *Handler) handleKnowledgeDetail(w http.ResponseWriter, r *http.Request) {
	idStr := strings.TrimPrefix(r.URL.Path, "/ui/knowledge/")
	id, err := uuid.Parse(idStr)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	data := struct {
		Artifact *db.KnowledgeArtifact
	}{}

	if h.pool != nil {
		art, err := db.GetArtifact(r.Context(), h.pool, id)
		if err != nil || art == nil {
			http.NotFound(w, r)
			return
		}
		data.Artifact = art
	}

	h.render(w, r, "knowledge_detail", "Knowledge", data)
}

// handleCollections serves GET /ui/collections.
func (h *Handler) handleCollections(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Collections []*db.KnowledgeCollection
	}{}

	scopeStr := r.URL.Query().Get("scope_id")
	if h.pool != nil && scopeStr != "" {
		sid, err := uuid.Parse(scopeStr)
		if err == nil {
			colls, err := db.ListCollections(r.Context(), h.pool, sid)
			if err == nil {
				data.Collections = colls
			}
		}
	}

	h.render(w, r, "collections", "Collections", data)
}

// handlePromotions serves GET /ui/promotions.
func (h *Handler) handlePromotions(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Promotions []*db.PromotionRequest
	}{}

	if h.pool != nil {
		proms, err := db.ListPendingPromotions(r.Context(), h.pool, uuid.Nil)
		if err == nil {
			data.Promotions = proms
		}
	}

	h.render(w, r, "promotions", "Promotion Queue", data)
}

// handleStaleness serves GET /ui/staleness.
func (h *Handler) handleStaleness(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Flags []*db.StalenessFlag
	}{}

	if h.pool != nil {
		flags, err := db.ListStalenessFlags(r.Context(), h.pool, "open", 50, 0)
		if err == nil {
			data.Flags = flags
		}
	}

	h.render(w, r, "staleness", "Staleness Flags", data)
}

// handleGraph serves GET /ui/graph.
func (h *Handler) handleGraph(w http.ResponseWriter, r *http.Request) {
	scopeStr := r.URL.Query().Get("scope_id")

	data := struct {
		ScopeID        string
		Entities       []*db.Entity
		Relations      []*db.Relation
		EntityNames    map[uuid.UUID]string
		RelationCounts map[uuid.UUID]int
	}{
		ScopeID:        scopeStr,
		EntityNames:    map[uuid.UUID]string{},
		RelationCounts: map[uuid.UUID]int{},
	}

	if h.pool != nil && scopeStr != "" {
		sid, err := uuid.Parse(scopeStr)
		if err == nil {
			ents, err := db.ListEntitiesByScope(r.Context(), h.pool, sid, "", 100, 0)
			if err == nil {
				data.Entities = ents
				for _, e := range ents {
					data.EntityNames[e.ID] = e.Name
				}
			}
			rels, err := db.ListRelationsByScope(r.Context(), h.pool, sid, 200, 0)
			if err == nil {
				data.Relations = rels
				for _, rel := range rels {
					data.RelationCounts[rel.SubjectID]++
					data.RelationCounts[rel.ObjectID]++
				}
			}
		}
	}

	h.render(w, r, "graph", "Entity Graph", data)
}

// handleSkills serves GET /ui/skills.
func (h *Handler) handleSkills(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Skills []*db.Skill
	}{}

	if h.pool != nil {
		skills, err := db.ListPublishedSkillsForAgent(r.Context(), h.pool, nil, "")
		if err == nil {
			data.Skills = skills
		}
	}

	h.render(w, r, "skills", "Skills", data)
}

// handlePrincipals serves GET /ui/principals.
func (h *Handler) handlePrincipals(w http.ResponseWriter, r *http.Request) {
	h.renderPrincipals(w, r, "")
}

// renderPrincipals renders the principals+scopes page with an optional form error.
func (h *Handler) renderPrincipals(w http.ResponseWriter, r *http.Request, formError string) {
	data := struct {
		Principals []*db.Principal
		Scopes     []*db.Scope
		FormError  string
	}{FormError: formError}

	if h.pool != nil {
		principals, err := db.ListPrincipals(r.Context(), h.pool, 50, 0)
		if err == nil {
			data.Principals = principals
		}
		scopes, err := db.ListScopes(r.Context(), h.pool, 50, 0)
		if err == nil {
			data.Scopes = scopes
		}
	}

	h.render(w, r, "principals", "Principals", data)
}

// handleCreateScope serves POST /ui/scopes.
func (h *Handler) handleCreateScope(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		h.renderPrincipals(w, r, "bad form data")
		return
	}
	kind := r.FormValue("kind")
	externalID := r.FormValue("external_id")
	name := r.FormValue("name")
	principalIDStr := r.FormValue("principal_id")
	parentIDStr := r.FormValue("parent_id")

	if kind == "" || externalID == "" || name == "" || principalIDStr == "" {
		h.renderPrincipals(w, r, "kind, external_id, name and principal are required")
		return
	}
	principalID, err := uuid.Parse(principalIDStr)
	if err != nil {
		h.renderPrincipals(w, r, "invalid principal id")
		return
	}
	var parentID *uuid.UUID
	if parentIDStr != "" {
		pid, err := uuid.Parse(parentIDStr)
		if err != nil {
			h.renderPrincipals(w, r, "invalid parent scope id")
			return
		}
		parentID = &pid
	}

	if h.pool == nil {
		h.renderPrincipals(w, r, "service unavailable")
		return
	}
	if _, err := db.CreateScope(r.Context(), h.pool, kind, externalID, name, parentID, principalID, nil); err != nil {
		h.renderPrincipals(w, r, err.Error())
		return
	}
	http.Redirect(w, r, "/ui/principals", http.StatusSeeOther)
}

// handleMetrics serves GET /ui/metrics.
func (h *Handler) handleMetrics(w http.ResponseWriter, r *http.Request) {
	h.render(w, r, "metrics", "Metrics", nil)
}
