package ui

import (
	"html/template"
	"net/http"
	"net/url"
	"strings"

	"github.com/simplyblock/postbrain/internal/authz"
	"github.com/simplyblock/postbrain/internal/db"
)

type uiPermission string

const (
	permissionNone  uiPermission = "none"
	permissionRead  uiPermission = "read"
	permissionWrite uiPermission = "write"
)

func requiredUIPermission(r *http.Request) uiPermission {
	if r.URL.Path == "/ui/logout" && r.Method == http.MethodPost {
		return permissionNone
	}
	switch r.Method {
	case http.MethodGet, http.MethodHead, http.MethodOptions:
		return permissionRead
	default:
		return permissionWrite
	}
}

func (h *Handler) hasUIPermission(r *http.Request, required uiPermission) bool {
	token := h.tokenFromCookie(r)
	if token == nil {
		return false
	}
	if required == permissionNone {
		return true
	}
	perms, err := authz.ParseTokenPermissions(token.Permissions)
	if err != nil {
		return false
	}
	switch required {
	case permissionRead:
		for _, p := range perms.Permissions() {
			_, op, err := p.Parse()
			if err == nil && op == authz.OperationRead {
				return true
			}
		}
		return false
	case permissionWrite:
		for _, p := range perms.Permissions() {
			_, op, err := p.Parse()
			if err == nil && op == authz.OperationWrite {
				return true
			}
		}
		return false
	default:
		return false
	}
}

func requiresPrincipalAdminSection(r *http.Request) bool {
	if strings.HasPrefix(r.URL.Path, "/ui/principals") {
		return true
	}
	return r.URL.Path == "/ui/memberships" || r.URL.Path == "/ui/memberships/delete" ||
		r.URL.Path == "/ui/scope-grants" || r.URL.Path == "/ui/scope-grants/delete"
}

// render renders a named template wrapped in the base layout.
// For HTMX requests (HX-Request: true header), renders only the content template.
// Scope info from context is automatically injected into the base layout.
func (h *Handler) render(w http.ResponseWriter, r *http.Request, tmplName string, title string, data any) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if r.Header.Get("HX-Request") == "true" {
		if err := h.templates.ExecuteTemplate(w, tmplName, data); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}
	var buf strings.Builder
	if err := h.templates.ExecuteTemplate(&buf, tmplName, data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	layout := "base"
	if tmplName == "login" {
		layout = "auth_base"
	}
	if err := h.templates.ExecuteTemplate(w, layout, struct {
		Title          string
		Content        template.HTML
		ShowPrincipals bool
		CurrentScope   *db.Scope
		Scopes         []*db.Scope
	}{
		Title:          title,
		Content:        template.HTML(buf.String()), //nolint:gosec // generated by our own templates
		ShowPrincipals: h.hasAnyPrincipalAdminRole(r.Context(), r),
		CurrentScope:   scopeFromContext(r.Context()),
		Scopes:         scopesFromContext(r.Context()),
	}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeHTTP routes /ui/* requests.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// Serve static files.
	if strings.HasPrefix(r.URL.Path, "/ui/static/") {
		http.StripPrefix("/ui/static/", http.FileServer(http.FS(h.staticFS))).ServeHTTP(w, r)
		return
	}
	// Login form and POST.
	if r.URL.Path == "/ui/login" {
		h.handleLogin(w, r)
		return
	}
	// Social login routes are unauthenticated.
	if strings.HasPrefix(r.URL.Path, "/ui/auth/") && r.Method == http.MethodGet {
		if strings.HasSuffix(r.URL.Path, "/callback") {
			h.handleSocialCallback(w, r)
			return
		}
		h.handleSocialStart(w, r)
		return
	}
	if r.URL.Path == "/ui/oauth/authorize" && r.Method == http.MethodGet {
		next := "/ui/oauth/authorize"
		if raw := r.URL.RawQuery; raw != "" {
			next += "?" + raw
		}
		if !h.authenticatedRedirect(w, r, "/ui/login?next="+url.QueryEscape(next)) {
			return
		}
		h.handleConsentGet(w, r)
		return
	}
	// Auth check for all other routes.
	if !h.authenticated(w, r) {
		return
	}
	if required := requiredUIPermission(r); required != permissionNone && !h.hasUIPermission(r, required) {
		http.Error(w, "forbidden: insufficient permissions", http.StatusForbidden)
		return
	}
	if requiresPrincipalAdminSection(r) && !h.hasAnyPrincipalAdminRole(r.Context(), r) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	// Try scoped route /ui/{scope-uuid}/... first.
	if h.dispatchScopedRoute(w, r) {
		return
	}

	// Redirect unscoped scope-requiring pages to the first authorized scope.
	for _, pfx := range scopeRequiredPrefixes {
		if r.URL.Path == pfx || strings.HasPrefix(r.URL.Path, pfx+"/") {
			scopes, _ := h.authorizedScopesForRequest(r.Context(), r)
			if len(scopes) == 0 {
				http.Error(w, "no authorized scopes", http.StatusForbidden)
				return
			}
			newPath := "/ui/" + scopes[0].ID.String() + r.URL.Path[len("/ui"):]
			if r.URL.RawQuery != "" {
				newPath += "?" + r.URL.RawQuery
			}
			code := http.StatusFound
			if r.Method != http.MethodGet && r.Method != http.MethodHead {
				code = http.StatusTemporaryRedirect
			}
			http.Redirect(w, r, newPath, code)
			return
		}
	}

	// Flat admin / auth / health routes (no scope in path).
	switch {
	case r.URL.Path == "/ui" || r.URL.Path == "/ui/":
		h.handleOverview(w, r)
	case strings.HasPrefix(r.URL.Path, "/ui/principals/") && r.Method == http.MethodPost:
		h.handleUpdatePrincipal(w, r)
	case r.URL.Path == "/ui/principals" && r.Method == http.MethodPost:
		h.handleCreatePrincipal(w, r)
	case r.URL.Path == "/ui/principals":
		h.handlePrincipals(w, r)
	case r.URL.Path == "/ui/scopes" && r.Method == http.MethodPost:
		h.handleCreateScope(w, r)
	case r.URL.Path == "/ui/scopes":
		h.handleScopes(w, r)
	case strings.HasSuffix(r.URL.Path, "/delete") && strings.HasPrefix(r.URL.Path, "/ui/scopes/") && r.Method == http.MethodPost:
		h.handleDeleteScope(w, r)
	case strings.HasSuffix(r.URL.Path, "/repo/sync/status") && strings.HasPrefix(r.URL.Path, "/ui/scopes/") && r.Method == http.MethodGet:
		h.handleSyncStatus(w, r)
	case strings.HasSuffix(r.URL.Path, "/repo/sync") && strings.HasPrefix(r.URL.Path, "/ui/scopes/") && r.Method == http.MethodPost:
		h.handleSyncScopeRepo(w, r)
	case strings.HasSuffix(r.URL.Path, "/repo") && strings.HasPrefix(r.URL.Path, "/ui/scopes/") && r.Method == http.MethodPost:
		h.handleSetScopeRepo(w, r)
	case strings.HasSuffix(r.URL.Path, "/owner") && strings.HasPrefix(r.URL.Path, "/ui/scopes/") && r.Method == http.MethodPost:
		h.handleSetScopeOwner(w, r)
	case r.URL.Path == "/ui/oauth/authorize" && r.Method == http.MethodPost:
		h.handleConsentPost(w, r)
	case r.URL.Path == "/ui/memberships" && r.Method == http.MethodPost:
		h.handleAddMembership(w, r)
	case r.URL.Path == "/ui/memberships/delete" && r.Method == http.MethodPost:
		h.handleDeleteMembership(w, r)
	case r.URL.Path == "/ui/scope-grants" && r.Method == http.MethodPost:
		h.handleCreateScopeGrant(w, r)
	case r.URL.Path == "/ui/scope-grants/delete" && r.Method == http.MethodPost:
		h.handleDeleteScopeGrant(w, r)
	case r.URL.Path == "/ui/tokens" && r.Method == http.MethodPost:
		h.handleCreateToken(w, r)
	case strings.HasSuffix(r.URL.Path, "/scopes") && strings.HasPrefix(r.URL.Path, "/ui/tokens/") && r.Method == http.MethodPost:
		h.handleUpdateTokenScopes(w, r)
	case strings.HasSuffix(r.URL.Path, "/revoke") && strings.HasPrefix(r.URL.Path, "/ui/tokens/") && r.Method == http.MethodPost:
		h.handleRevokeToken(w, r)
	case r.URL.Path == "/ui/tokens":
		h.handleTokens(w, r)
	case r.URL.Path == "/ui/logout" && r.Method == http.MethodPost:
		h.handleLogout(w, r)
	case r.URL.Path == "/ui/metrics":
		h.handleMetrics(w, r)
	default:
		http.NotFound(w, r)
	}
}

// handleOverview serves GET /ui — server health and schema version.
func (h *Handler) handleOverview(w http.ResponseWriter, r *http.Request) {
	data := struct {
		Status          string
		SchemaVersion   uint
		ExpectedVersion uint
		SchemaDirty     bool
	}{
		Status:          "ok",
		SchemaVersion:   0,
		ExpectedVersion: 0,
		SchemaDirty:     false,
	}
	if h.pool != nil {
		sv, dirty, err := db.SchemaVersion(r.Context(), h.pool)
		if err == nil {
			data.SchemaVersion = sv
			data.SchemaDirty = dirty
		} else {
			data.Status = "degraded"
		}
	}
	h.render(w, r, "health", "Overview", data)
}
