// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAllScopeIDs = `-- name: GetAllScopeIDs :many
SELECT id FROM scopes
`

func (q *Queries) GetAllScopeIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllScopeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendantMembershipRoles = `-- name: GetDescendantMembershipRoles :many
WITH RECURSIVE principal_ancestry(id) AS (
    SELECT $1::uuid
    UNION
    SELECT pm2.parent_id
    FROM principal_memberships pm2
    JOIN principal_ancestry pa ON pm2.member_id = pa.id
)
SELECT pm.role
FROM principal_memberships pm
JOIN scopes owned  ON pm.parent_id = owned.principal_id
JOIN scopes target ON target.path @> owned.path
WHERE pm.member_id IN (SELECT id FROM principal_ancestry)
  AND target.id = $2
  AND owned.id != target.id
`

type GetDescendantMembershipRolesParams struct {
	Column1 uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetDescendantMembershipRoles(ctx context.Context, arg GetDescendantMembershipRolesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getDescendantMembershipRoles, arg.Column1, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDescendantScopeGrantPermissions = `-- name: GetDescendantScopeGrantPermissions :many
SELECT sg.permissions
FROM scope_grants sg
JOIN scopes descendant ON sg.scope_id = descendant.id
JOIN scopes target     ON target.path @> descendant.path
WHERE sg.principal_id = $1
  AND target.id = $2
  AND descendant.id != target.id
  AND (sg.expires_at IS NULL OR sg.expires_at > now())
`

type GetDescendantScopeGrantPermissionsParams struct {
	PrincipalID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetDescendantScopeGrantPermissions(ctx context.Context, arg GetDescendantScopeGrantPermissionsParams) ([][]string, error) {
	rows, err := q.db.Query(ctx, getDescendantScopeGrantPermissions, arg.PrincipalID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]string{}
	for rows.Next() {
		var permissions []string
		if err := rows.Scan(&permissions); err != nil {
			return nil, err
		}
		items = append(items, permissions)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEffectiveMembershipRole = `-- name: GetEffectiveMembershipRole :one
WITH RECURSIVE principal_ancestry(id) AS (
    SELECT $1::uuid
    UNION
    SELECT pm2.parent_id
    FROM principal_memberships pm2
    JOIN principal_ancestry pa ON pm2.member_id = pa.id
)
SELECT pm.role
FROM principal_memberships pm
JOIN (
    SELECT DISTINCT s.principal_id
    FROM scopes s
    JOIN scopes t ON s.path @> t.path
    WHERE t.id = $2
) owners ON pm.parent_id = owners.principal_id
WHERE pm.member_id IN (SELECT id FROM principal_ancestry)
ORDER BY CASE pm.role
    WHEN 'owner'  THEN 1
    WHEN 'admin'  THEN 2
    WHEN 'member' THEN 3
    ELSE 4
END
LIMIT 1
`

type GetEffectiveMembershipRoleParams struct {
	Column1 uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetEffectiveMembershipRole(ctx context.Context, arg GetEffectiveMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getEffectiveMembershipRole, arg.Column1, arg.ID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getPrincipalSystemAdmin = `-- name: GetPrincipalSystemAdmin :one
SELECT is_system_admin FROM principals WHERE id = $1
`

func (q *Queries) GetPrincipalSystemAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getPrincipalSystemAdmin, id)
	var is_system_admin bool
	err := row.Scan(&is_system_admin)
	return is_system_admin, err
}

const getReachableScopeIDs = `-- name: GetReachableScopeIDs :many
WITH RECURSIVE
principal_ancestry AS (
    SELECT $1::uuid AS id
    UNION
    SELECT pm.parent_id
    FROM principal_memberships pm
    JOIN principal_ancestry pa ON pm.member_id = pa.id
),
membership_scopes AS (
    SELECT id FROM scopes WHERE principal_id IN (SELECT id FROM principal_ancestry)
),
grant_scopes AS (
    SELECT DISTINCT scope_id AS id
    FROM scope_grants
    WHERE principal_id = $1
      AND (expires_at IS NULL OR expires_at > now())
),
direct_scopes AS (
    SELECT id FROM membership_scopes
    UNION
    SELECT id FROM grant_scopes
),
upward_scopes AS (
    SELECT DISTINCT ancestor.id
    FROM scopes ancestor
    JOIN scopes direct ON ancestor.path @> direct.path AND ancestor.id != direct.id
    WHERE direct.id IN (SELECT id FROM direct_scopes)
)
SELECT id FROM direct_scopes
UNION
SELECT id FROM upward_scopes
`

func (q *Queries) GetReachableScopeIDs(ctx context.Context, dollar_1 uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getReachableScopeIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeGrantPermissions = `-- name: GetScopeGrantPermissions :many
SELECT sg.permissions
FROM scope_grants sg
JOIN scopes ancestor ON sg.scope_id = ancestor.id
JOIN scopes target   ON ancestor.path @> target.path
WHERE sg.principal_id = $1
  AND target.id = $2
  AND (sg.expires_at IS NULL OR sg.expires_at > now())
`

type GetScopeGrantPermissionsParams struct {
	PrincipalID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetScopeGrantPermissions(ctx context.Context, arg GetScopeGrantPermissionsParams) ([][]string, error) {
	rows, err := q.db.Query(ctx, getScopeGrantPermissions, arg.PrincipalID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]string{}
	for rows.Next() {
		var permissions []string
		if err := rows.Scan(&permissions); err != nil {
			return nil, err
		}
		items = append(items, permissions)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const principalOwnsDescendant = `-- name: PrincipalOwnsDescendant :one
SELECT EXISTS (
    SELECT 1
    FROM scopes target
    JOIN scopes owned ON target.path @> owned.path
    WHERE target.id = $1
      AND owned.id != target.id
      AND owned.principal_id = $2
)
`

type PrincipalOwnsDescendantParams struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
}

func (q *Queries) PrincipalOwnsDescendant(ctx context.Context, arg PrincipalOwnsDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, principalOwnsDescendant, arg.ID, arg.PrincipalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const principalOwnsTargetOrAncestor = `-- name: PrincipalOwnsTargetOrAncestor :one
SELECT EXISTS (
    SELECT 1
    FROM scopes owner_scope
    JOIN scopes target ON owner_scope.path @> target.path
    WHERE target.id = $2
      AND owner_scope.principal_id = $1
)
`

type PrincipalOwnsTargetOrAncestorParams struct {
	PrincipalID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) PrincipalOwnsTargetOrAncestor(ctx context.Context, arg PrincipalOwnsTargetOrAncestorParams) (bool, error) {
	row := q.db.QueryRow(ctx, principalOwnsTargetOrAncestor, arg.PrincipalID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const scopeExists = `-- name: ScopeExists :one
SELECT EXISTS(SELECT 1 FROM scopes WHERE id = $1)
`

func (q *Queries) ScopeExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, scopeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
