// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCollectionItem = `-- name: AddCollectionItem :exec
INSERT INTO knowledge_collection_items (collection_id, artifact_id, added_by)
VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type AddCollectionItemParams struct {
	CollectionID uuid.UUID
	ArtifactID   uuid.UUID
	AddedBy      uuid.UUID
}

func (q *Queries) AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error {
	_, err := q.db.Exec(ctx, addCollectionItem, arg.CollectionID, arg.ArtifactID, arg.AddedBy)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO knowledge_collections (scope_id, owner_id, slug, name, description, visibility, meta)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, scope_id, owner_id, slug, name, description, visibility, meta, created_at, updated_at
`

type CreateCollectionParams struct {
	ScopeID     uuid.UUID
	OwnerID     uuid.UUID
	Slug        string
	Name        string
	Description *string
	Visibility  string
	Meta        []byte
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (*KnowledgeCollection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ScopeID,
		arg.OwnerID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.Meta,
	)
	var i KnowledgeCollection
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, scope_id, owner_id, slug, name, description, visibility, meta, created_at, updated_at
FROM knowledge_collections WHERE id=$1
`

func (q *Queries) GetCollection(ctx context.Context, id uuid.UUID) (*KnowledgeCollection, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i KnowledgeCollection
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, scope_id, owner_id, slug, name, description, visibility, meta, created_at, updated_at
FROM knowledge_collections WHERE scope_id=$1 AND slug=$2
`

type GetCollectionBySlugParams struct {
	ScopeID uuid.UUID
	Slug    string
}

func (q *Queries) GetCollectionBySlug(ctx context.Context, arg GetCollectionBySlugParams) (*KnowledgeCollection, error) {
	row := q.db.QueryRow(ctx, getCollectionBySlug, arg.ScopeID, arg.Slug)
	var i KnowledgeCollection
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCollectionItems = `-- name: ListCollectionItems :many
SELECT ka.id, ka.knowledge_type, ka.owner_scope_id, ka.author_id,
    ka.visibility, ka.status, ka.published_at, ka.deprecated_at, ka.review_required,
    ka.title, ka.content, ka.summary, ka.embedding, ka.embedding_model_id, ka.meta,
    ka.endorsement_count, ka.access_count, ka.last_accessed,
    ka.version, ka.previous_version, ka.source_memory_id, ka.source_ref,
    ka.created_at, ka.updated_at
FROM knowledge_artifacts ka
JOIN knowledge_collection_items kci ON kci.artifact_id = ka.id
WHERE kci.collection_id = $1
ORDER BY kci.position, kci.added_at
`

func (q *Queries) ListCollectionItems(ctx context.Context, collectionID uuid.UUID) ([]*KnowledgeArtifact, error) {
	rows, err := q.db.Query(ctx, listCollectionItems, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeArtifact{}
	for rows.Next() {
		var i KnowledgeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, scope_id, owner_id, slug, name, description, visibility, meta, created_at, updated_at
FROM knowledge_collections WHERE scope_id=$1 ORDER BY name
`

func (q *Queries) ListCollections(ctx context.Context, scopeID uuid.UUID) ([]*KnowledgeCollection, error) {
	rows, err := q.db.Query(ctx, listCollections, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeCollection{}
	for rows.Next() {
		var i KnowledgeCollection
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.OwnerID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionItem = `-- name: RemoveCollectionItem :exec
DELETE FROM knowledge_collection_items WHERE collection_id=$1 AND artifact_id=$2
`

type RemoveCollectionItemParams struct {
	CollectionID uuid.UUID
	ArtifactID   uuid.UUID
}

func (q *Queries) RemoveCollectionItem(ctx context.Context, arg RemoveCollectionItemParams) error {
	_, err := q.db.Exec(ctx, removeCollectionItem, arg.CollectionID, arg.ArtifactID)
	return err
}
