// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consolidations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createConsolidation = `-- name: CreateConsolidation :one
INSERT INTO consolidations (scope_id, source_ids, result_id, strategy, reason)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, scope_id, source_ids, result_id, strategy, reason, created_at
`

type CreateConsolidationParams struct {
	ScopeID   uuid.UUID
	SourceIds []uuid.UUID
	ResultID  *uuid.UUID
	Strategy  string
	Reason    *string
}

func (q *Queries) CreateConsolidation(ctx context.Context, arg CreateConsolidationParams) (*Consolidation, error) {
	row := q.db.QueryRow(ctx, createConsolidation,
		arg.ScopeID,
		arg.SourceIds,
		arg.ResultID,
		arg.Strategy,
		arg.Reason,
	)
	var i Consolidation
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.SourceIds,
		&i.ResultID,
		&i.Strategy,
		&i.Reason,
		&i.CreatedAt,
	)
	return &i, err
}
