// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding_models.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const getActiveCodeModel = `-- name: GetActiveCodeModel :one
SELECT id, slug, dimensions, content_type, is_active, description, created_at
FROM ai_models WHERE model_type = 'embedding' AND content_type = 'code' AND is_active = true LIMIT 1
`

type GetActiveCodeModelRow struct {
	ID          uuid.UUID
	Slug        string
	Dimensions  int32
	ContentType string
	IsActive    bool
	Description *string
	CreatedAt   time.Time
}

func (q *Queries) GetActiveCodeModel(ctx context.Context) (*GetActiveCodeModelRow, error) {
	row := q.db.QueryRow(ctx, getActiveCodeModel)
	var i GetActiveCodeModelRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Dimensions,
		&i.ContentType,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
	)
	return &i, err
}

const getActiveTextModel = `-- name: GetActiveTextModel :one
SELECT id, slug, dimensions, content_type, is_active, description, created_at
FROM ai_models WHERE model_type = 'embedding' AND content_type = 'text' AND is_active = true LIMIT 1
`

type GetActiveTextModelRow struct {
	ID          uuid.UUID
	Slug        string
	Dimensions  int32
	ContentType string
	IsActive    bool
	Description *string
	CreatedAt   time.Time
}

func (q *Queries) GetActiveTextModel(ctx context.Context) (*GetActiveTextModelRow, error) {
	row := q.db.QueryRow(ctx, getActiveTextModel)
	var i GetActiveTextModelRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Dimensions,
		&i.ContentType,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
	)
	return &i, err
}

const getMemoriesNeedingCodeReembed = `-- name: GetMemoriesNeedingCodeReembed :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, created_at, updated_at
FROM memories
WHERE is_active = true
  AND content_kind = 'code'
  AND (embedding_code_model_id IS NULL OR embedding_code_model_id != $1)
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type GetMemoriesNeedingCodeReembedParams struct {
	EmbeddingCodeModelID *uuid.UUID
	Limit                int32
	Offset               int32
}

type GetMemoriesNeedingCodeReembedRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetMemoriesNeedingCodeReembed(ctx context.Context, arg GetMemoriesNeedingCodeReembedParams) ([]*GetMemoriesNeedingCodeReembedRow, error) {
	rows, err := q.db.Query(ctx, getMemoriesNeedingCodeReembed, arg.EmbeddingCodeModelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMemoriesNeedingCodeReembedRow{}
	for rows.Next() {
		var i GetMemoriesNeedingCodeReembedRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoriesNeedingTextReembed = `-- name: GetMemoriesNeedingTextReembed :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, created_at, updated_at
FROM memories
WHERE is_active = true
  AND (embedding_model_id IS NULL OR embedding_model_id != $1)
  AND content_kind = 'text'
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type GetMemoriesNeedingTextReembedParams struct {
	EmbeddingModelID *uuid.UUID
	Limit            int32
	Offset           int32
}

type GetMemoriesNeedingTextReembedRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetMemoriesNeedingTextReembed(ctx context.Context, arg GetMemoriesNeedingTextReembedParams) ([]*GetMemoriesNeedingTextReembedRow, error) {
	rows, err := q.db.Query(ctx, getMemoriesNeedingTextReembed, arg.EmbeddingModelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMemoriesNeedingTextReembedRow{}
	for rows.Next() {
		var i GetMemoriesNeedingTextReembedRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryCodeEmbedding = `-- name: UpdateMemoryCodeEmbedding :exec
UPDATE memories SET embedding_code = $2, embedding_code_model_id = $3, updated_at = now()
WHERE id = $1
`

type UpdateMemoryCodeEmbeddingParams struct {
	ID                   uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
}

func (q *Queries) UpdateMemoryCodeEmbedding(ctx context.Context, arg UpdateMemoryCodeEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateMemoryCodeEmbedding, arg.ID, arg.EmbeddingCode, arg.EmbeddingCodeModelID)
	return err
}

const updateMemoryTextEmbedding = `-- name: UpdateMemoryTextEmbedding :exec
UPDATE memories SET embedding = $2, embedding_model_id = $3, updated_at = now()
WHERE id = $1
`

type UpdateMemoryTextEmbeddingParams struct {
	ID               uuid.UUID
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpdateMemoryTextEmbedding(ctx context.Context, arg UpdateMemoryTextEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateMemoryTextEmbedding, arg.ID, arg.Embedding, arg.EmbeddingModelID)
	return err
}

const upsertEmbeddingModel = `-- name: UpsertEmbeddingModel :one
INSERT INTO ai_models (slug, dimensions, content_type, model_type, is_active)
VALUES ($1, $2, $3, 'embedding', $4)
ON CONFLICT (slug) DO UPDATE SET
  dimensions = EXCLUDED.dimensions,
  is_active = EXCLUDED.is_active,
  content_type = EXCLUDED.content_type,
  model_type = EXCLUDED.model_type
RETURNING id, slug, dimensions, content_type, is_active, description, created_at
`

type UpsertEmbeddingModelParams struct {
	Slug        string
	Dimensions  int32
	ContentType string
	IsActive    bool
}

type UpsertEmbeddingModelRow struct {
	ID          uuid.UUID
	Slug        string
	Dimensions  int32
	ContentType string
	IsActive    bool
	Description *string
	CreatedAt   time.Time
}

func (q *Queries) UpsertEmbeddingModel(ctx context.Context, arg UpsertEmbeddingModelParams) (*UpsertEmbeddingModelRow, error) {
	row := q.db.QueryRow(ctx, upsertEmbeddingModel,
		arg.Slug,
		arg.Dimensions,
		arg.ContentType,
		arg.IsActive,
	)
	var i UpsertEmbeddingModelRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Dimensions,
		&i.ContentType,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
	)
	return &i, err
}
