// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const getEntityByCanonical = `-- name: GetEntityByCanonical :one
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities WHERE scope_id=$1 AND entity_type=$2 AND canonical=$3
`

type GetEntityByCanonicalParams struct {
	ScopeID    uuid.UUID
	EntityType string
	Canonical  string
}

func (q *Queries) GetEntityByCanonical(ctx context.Context, arg GetEntityByCanonicalParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByCanonical, arg.ScopeID, arg.EntityType, arg.Canonical)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EntityType,
		&i.Name,
		&i.Canonical,
		&i.Meta,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const linkMemoryToEntity = `-- name: LinkMemoryToEntity :exec
INSERT INTO memory_entities (memory_id, entity_id, role) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type LinkMemoryToEntityParams struct {
	MemoryID uuid.UUID
	EntityID uuid.UUID
	Role     *string
}

func (q *Queries) LinkMemoryToEntity(ctx context.Context, arg LinkMemoryToEntityParams) error {
	_, err := q.db.Exec(ctx, linkMemoryToEntity, arg.MemoryID, arg.EntityID, arg.Role)
	return err
}

const listEntitiesByScope = `-- name: ListEntitiesByScope :many
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities
WHERE scope_id=$1 AND ($2='' OR entity_type=$2)
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListEntitiesByScopeParams struct {
	ScopeID uuid.UUID
	Column2 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListEntitiesByScope(ctx context.Context, arg ListEntitiesByScopeParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByScope,
		arg.ScopeID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.EntityType,
			&i.Name,
			&i.Canonical,
			&i.Meta,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByScope = `-- name: ListRelationsByScope :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, created_at
FROM relations
WHERE scope_id=$1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type ListRelationsByScopeParams struct {
	ScopeID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListRelationsByScope(ctx context.Context, arg ListRelationsByScopeParams) ([]*Relation, error) {
	rows, err := q.db.Query(ctx, listRelationsByScope, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Relation{}
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsForEntity = `-- name: ListRelationsForEntity :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, created_at
FROM relations WHERE subject_id=$1 OR object_id=$1
ORDER BY created_at
`

func (q *Queries) ListRelationsForEntity(ctx context.Context, subjectID uuid.UUID) ([]*Relation, error) {
	rows, err := q.db.Query(ctx, listRelationsForEntity, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Relation{}
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsForEntityByPredicate = `-- name: ListRelationsForEntityByPredicate :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, created_at
FROM relations
WHERE (subject_id = $1 OR object_id = $1) AND predicate = $2
ORDER BY created_at
`

type ListRelationsForEntityByPredicateParams struct {
	SubjectID uuid.UUID
	Predicate string
}

func (q *Queries) ListRelationsForEntityByPredicate(ctx context.Context, arg ListRelationsForEntityByPredicateParams) ([]*Relation, error) {
	rows, err := q.db.Query(ctx, listRelationsForEntityByPredicate, arg.SubjectID, arg.Predicate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Relation{}
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (scope_id, entity_type, name, canonical, meta, embedding, embedding_model_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (scope_id, entity_type, canonical)
DO UPDATE SET name=EXCLUDED.name, meta=EXCLUDED.meta,
              embedding=EXCLUDED.embedding, embedding_model_id=EXCLUDED.embedding_model_id,
              updated_at=now()
RETURNING id, scope_id, entity_type, name, canonical, meta,
          embedding, embedding_model_id, created_at, updated_at
`

type UpsertEntityParams struct {
	ScopeID          uuid.UUID
	EntityType       string
	Name             string
	Canonical        string
	Meta             []byte
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.ScopeID,
		arg.EntityType,
		arg.Name,
		arg.Canonical,
		arg.Meta,
		arg.Embedding,
		arg.EmbeddingModelID,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EntityType,
		&i.Name,
		&i.Canonical,
		&i.Meta,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO relations (scope_id, subject_id, predicate, object_id, confidence, source_memory)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (scope_id, subject_id, predicate, object_id)
DO UPDATE SET confidence=EXCLUDED.confidence, source_memory=EXCLUDED.source_memory
RETURNING id, scope_id, subject_id, predicate, object_id, confidence, source_memory, created_at
`

type UpsertRelationParams struct {
	ScopeID      uuid.UUID
	SubjectID    uuid.UUID
	Predicate    string
	ObjectID     uuid.UUID
	Confidence   float64
	SourceMemory *uuid.UUID
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (*Relation, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.ScopeID,
		arg.SubjectID,
		arg.Predicate,
		arg.ObjectID,
		arg.Confidence,
		arg.SourceMemory,
	)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.SubjectID,
		&i.Predicate,
		&i.ObjectID,
		&i.Confidence,
		&i.SourceMemory,
		&i.CreatedAt,
	)
	return &i, err
}
