// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const deleteArtifactEntityLinks = `-- name: DeleteArtifactEntityLinks :exec
DELETE FROM artifact_entities WHERE artifact_id = $1
`

func (q *Queries) DeleteArtifactEntityLinks(ctx context.Context, artifactID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifactEntityLinks, artifactID)
	return err
}

const deleteRelationsBySourceFile = `-- name: DeleteRelationsBySourceFile :exec
DELETE FROM relations WHERE scope_id = $1 AND source_file = $2
`

type DeleteRelationsBySourceFileParams struct {
	ScopeID    uuid.UUID
	SourceFile *string
}

// Used by incremental re-index to invalidate stale edges before re-extraction.
func (q *Queries) DeleteRelationsBySourceFile(ctx context.Context, arg DeleteRelationsBySourceFileParams) error {
	_, err := q.db.Exec(ctx, deleteRelationsBySourceFile, arg.ScopeID, arg.SourceFile)
	return err
}

const findEntitiesBySuffix = `-- name: FindEntitiesBySuffix :many
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities
WHERE scope_id = $1
  AND (
    canonical = $2
    OR canonical LIKE ('%.' || $2)
    OR canonical LIKE ('%::' || $2)
    OR canonical LIKE ('%#' || $2)
  )
ORDER BY length(canonical) ASC
LIMIT 5
`

type FindEntitiesBySuffixParams struct {
	ScopeID   uuid.UUID
	Canonical string
}

// Heuristic resolution: match call/type targets against entities whose
// canonical name equals $2, ends with ".$2", or ends with "::$2".
// Returns up to 5 candidates ordered by shortest name first (most specific).
func (q *Queries) FindEntitiesBySuffix(ctx context.Context, arg FindEntitiesBySuffixParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, findEntitiesBySuffix, arg.ScopeID, arg.Canonical)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.EntityType,
			&i.Name,
			&i.Canonical,
			&i.Meta,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityByCanonical = `-- name: GetEntityByCanonical :one
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities WHERE scope_id=$1 AND entity_type=$2 AND canonical=$3
`

type GetEntityByCanonicalParams struct {
	ScopeID    uuid.UUID
	EntityType string
	Canonical  string
}

func (q *Queries) GetEntityByCanonical(ctx context.Context, arg GetEntityByCanonicalParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByCanonical, arg.ScopeID, arg.EntityType, arg.Canonical)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EntityType,
		&i.Name,
		&i.Canonical,
		&i.Meta,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities WHERE id = $1
`

func (q *Queries) GetEntityByID(ctx context.Context, id uuid.UUID) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EntityType,
		&i.Name,
		&i.Canonical,
		&i.Meta,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const linkArtifactToEntity = `-- name: LinkArtifactToEntity :exec
INSERT INTO artifact_entities (artifact_id, entity_id, role) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type LinkArtifactToEntityParams struct {
	ArtifactID uuid.UUID
	EntityID   uuid.UUID
	Role       *string
}

func (q *Queries) LinkArtifactToEntity(ctx context.Context, arg LinkArtifactToEntityParams) error {
	_, err := q.db.Exec(ctx, linkArtifactToEntity, arg.ArtifactID, arg.EntityID, arg.Role)
	return err
}

const linkMemoryToEntity = `-- name: LinkMemoryToEntity :exec
INSERT INTO memory_entities (memory_id, entity_id, role) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type LinkMemoryToEntityParams struct {
	MemoryID uuid.UUID
	EntityID uuid.UUID
	Role     *string
}

func (q *Queries) LinkMemoryToEntity(ctx context.Context, arg LinkMemoryToEntityParams) error {
	_, err := q.db.Exec(ctx, linkMemoryToEntity, arg.MemoryID, arg.EntityID, arg.Role)
	return err
}

const listEntitiesByCanonical = `-- name: ListEntitiesByCanonical :many
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities
WHERE scope_id=$1 AND canonical=$2 AND entity_type != $3
`

type ListEntitiesByCanonicalParams struct {
	ScopeID    uuid.UUID
	Canonical  string
	EntityType string
}

func (q *Queries) ListEntitiesByCanonical(ctx context.Context, arg ListEntitiesByCanonicalParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByCanonical, arg.ScopeID, arg.Canonical, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.EntityType,
			&i.Name,
			&i.Canonical,
			&i.Meta,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByScope = `-- name: ListEntitiesByScope :many
SELECT id, scope_id, entity_type, name, canonical, meta,
       embedding, embedding_model_id, created_at, updated_at
FROM entities
WHERE scope_id=$1 AND ($2='' OR entity_type=$2)
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListEntitiesByScopeParams struct {
	ScopeID uuid.UUID
	Column2 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListEntitiesByScope(ctx context.Context, arg ListEntitiesByScopeParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByScope,
		arg.ScopeID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.EntityType,
			&i.Name,
			&i.Canonical,
			&i.Meta,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRelations = `-- name: ListIncomingRelations :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
FROM relations
WHERE scope_id = $1 AND object_id = $2 AND ($3 = '' OR predicate = $3)
ORDER BY confidence DESC, created_at
`

type ListIncomingRelationsParams struct {
	ScopeID  uuid.UUID
	ObjectID uuid.UUID
	Column3  interface{}
}

type ListIncomingRelationsRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

// Relations where this entity is the object, optionally filtered by predicate.
func (q *Queries) ListIncomingRelations(ctx context.Context, arg ListIncomingRelationsParams) ([]*ListIncomingRelationsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRelations, arg.ScopeID, arg.ObjectID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListIncomingRelationsRow{}
	for rows.Next() {
		var i ListIncomingRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.SourceArtifact,
			&i.SourceFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRelations = `-- name: ListOutgoingRelations :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
FROM relations
WHERE scope_id = $1 AND subject_id = $2 AND ($3 = '' OR predicate = $3)
ORDER BY confidence DESC, created_at
`

type ListOutgoingRelationsParams struct {
	ScopeID   uuid.UUID
	SubjectID uuid.UUID
	Column3   interface{}
}

type ListOutgoingRelationsRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

// Relations where this entity is the subject, optionally filtered by predicate.
func (q *Queries) ListOutgoingRelations(ctx context.Context, arg ListOutgoingRelationsParams) ([]*ListOutgoingRelationsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRelations, arg.ScopeID, arg.SubjectID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListOutgoingRelationsRow{}
	for rows.Next() {
		var i ListOutgoingRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.SourceArtifact,
			&i.SourceFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsByScope = `-- name: ListRelationsByScope :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
FROM relations
WHERE scope_id=$1
ORDER BY created_at
`

type ListRelationsByScopeRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

func (q *Queries) ListRelationsByScope(ctx context.Context, scopeID uuid.UUID) ([]*ListRelationsByScopeRow, error) {
	rows, err := q.db.Query(ctx, listRelationsByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRelationsByScopeRow{}
	for rows.Next() {
		var i ListRelationsByScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.SourceArtifact,
			&i.SourceFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsForEntity = `-- name: ListRelationsForEntity :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
FROM relations WHERE subject_id=$1 OR object_id=$1
ORDER BY created_at
`

type ListRelationsForEntityRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

func (q *Queries) ListRelationsForEntity(ctx context.Context, subjectID uuid.UUID) ([]*ListRelationsForEntityRow, error) {
	rows, err := q.db.Query(ctx, listRelationsForEntity, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRelationsForEntityRow{}
	for rows.Next() {
		var i ListRelationsForEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.SourceArtifact,
			&i.SourceFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsForEntityByPredicate = `-- name: ListRelationsForEntityByPredicate :many
SELECT id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
FROM relations
WHERE (subject_id = $1 OR object_id = $1) AND predicate = $2
ORDER BY created_at
`

type ListRelationsForEntityByPredicateParams struct {
	SubjectID uuid.UUID
	Predicate string
}

type ListRelationsForEntityByPredicateRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

func (q *Queries) ListRelationsForEntityByPredicate(ctx context.Context, arg ListRelationsForEntityByPredicateParams) ([]*ListRelationsForEntityByPredicateRow, error) {
	rows, err := q.db.Query(ctx, listRelationsForEntityByPredicate, arg.SubjectID, arg.Predicate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRelationsForEntityByPredicateRow{}
	for rows.Next() {
		var i ListRelationsForEntityByPredicateRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.SubjectID,
			&i.Predicate,
			&i.ObjectID,
			&i.Confidence,
			&i.SourceMemory,
			&i.SourceArtifact,
			&i.SourceFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (scope_id, entity_type, name, canonical, meta, embedding, embedding_model_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (scope_id, entity_type, canonical)
DO UPDATE SET name=EXCLUDED.name, meta=EXCLUDED.meta,
              embedding=EXCLUDED.embedding, embedding_model_id=EXCLUDED.embedding_model_id,
              updated_at=now()
RETURNING id, scope_id, entity_type, name, canonical, meta,
          embedding, embedding_model_id, created_at, updated_at
`

type UpsertEntityParams struct {
	ScopeID          uuid.UUID
	EntityType       string
	Name             string
	Canonical        string
	Meta             []byte
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.ScopeID,
		arg.EntityType,
		arg.Name,
		arg.Canonical,
		arg.Meta,
		arg.Embedding,
		arg.EmbeddingModelID,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EntityType,
		&i.Name,
		&i.Canonical,
		&i.Meta,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertRelation = `-- name: UpsertRelation :one
INSERT INTO relations (scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (scope_id, subject_id, predicate, object_id)
DO UPDATE SET confidence=EXCLUDED.confidence, source_memory=EXCLUDED.source_memory,
              source_artifact=EXCLUDED.source_artifact, source_file=EXCLUDED.source_file
RETURNING id, scope_id, subject_id, predicate, object_id, confidence, source_memory, source_artifact, source_file, created_at
`

type UpsertRelationParams struct {
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
}

type UpsertRelationRow struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	SourceArtifact *uuid.UUID
	SourceFile     *string
	CreatedAt      time.Time
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) (*UpsertRelationRow, error) {
	row := q.db.QueryRow(ctx, upsertRelation,
		arg.ScopeID,
		arg.SubjectID,
		arg.Predicate,
		arg.ObjectID,
		arg.Confidence,
		arg.SourceMemory,
		arg.SourceArtifact,
		arg.SourceFile,
	)
	var i UpsertRelationRow
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.SubjectID,
		&i.Predicate,
		&i.ObjectID,
		&i.Confidence,
		&i.SourceMemory,
		&i.SourceArtifact,
		&i.SourceFile,
		&i.CreatedAt,
	)
	return &i, err
}
