// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO knowledge_artifacts
(knowledge_type, owner_scope_id, author_id, visibility, status,
 published_at, deprecated_at, review_required,
 title, content, summary, embedding, embedding_model_id, meta,
 version, previous_version, source_memory_id, source_ref)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
        NULLIF($16, '00000000-0000-0000-0000-000000000000'::uuid),
        NULLIF($17, '00000000-0000-0000-0000-000000000000'::uuid),
        $18)
RETURNING id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
`

type CreateArtifactParams struct {
	KnowledgeType    string
	OwnerScopeID     uuid.UUID
	AuthorID         uuid.UUID
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	Meta             []byte
	Version          int32
	Column16         interface{}
	Column17         interface{}
	SourceRef        *string
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (*KnowledgeArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.KnowledgeType,
		arg.OwnerScopeID,
		arg.AuthorID,
		arg.Visibility,
		arg.Status,
		arg.PublishedAt,
		arg.DeprecatedAt,
		arg.ReviewRequired,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Embedding,
		arg.EmbeddingModelID,
		arg.Meta,
		arg.Version,
		arg.Column16,
		arg.Column17,
		arg.SourceRef,
	)
	var i KnowledgeArtifact
	err := row.Scan(
		&i.ID,
		&i.KnowledgeType,
		&i.OwnerScopeID,
		&i.AuthorID,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.Meta,
		&i.EndorsementCount,
		&i.AccessCount,
		&i.LastAccessed,
		&i.Version,
		&i.PreviousVersion,
		&i.SourceMemoryID,
		&i.SourceRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createEndorsement = `-- name: CreateEndorsement :one
INSERT INTO knowledge_endorsements (artifact_id, endorser_id, note)
VALUES ($1,$2,$3)
RETURNING id, artifact_id, endorser_id, note, created_at
`

type CreateEndorsementParams struct {
	ArtifactID uuid.UUID
	EndorserID uuid.UUID
	Note       *string
}

func (q *Queries) CreateEndorsement(ctx context.Context, arg CreateEndorsementParams) (*KnowledgeEndorsement, error) {
	row := q.db.QueryRow(ctx, createEndorsement, arg.ArtifactID, arg.EndorserID, arg.Note)
	var i KnowledgeEndorsement
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.EndorserID,
		&i.Note,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM knowledge_artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
FROM knowledge_artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (*KnowledgeArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i KnowledgeArtifact
	err := row.Scan(
		&i.ID,
		&i.KnowledgeType,
		&i.OwnerScopeID,
		&i.AuthorID,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.Meta,
		&i.EndorsementCount,
		&i.AccessCount,
		&i.LastAccessed,
		&i.Version,
		&i.PreviousVersion,
		&i.SourceMemoryID,
		&i.SourceRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getArtifactHistory = `-- name: GetArtifactHistory :many
SELECT id, artifact_id, version, content, summary, changed_by, change_note, created_at
FROM knowledge_history
WHERE artifact_id = $1
ORDER BY version DESC
`

func (q *Queries) GetArtifactHistory(ctx context.Context, artifactID uuid.UUID) ([]*KnowledgeHistory, error) {
	rows, err := q.db.Query(ctx, getArtifactHistory, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeHistory{}
	for rows.Next() {
		var i KnowledgeHistory
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.Content,
			&i.Summary,
			&i.ChangedBy,
			&i.ChangeNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndorsementByEndorser = `-- name: GetEndorsementByEndorser :one
SELECT id, artifact_id, endorser_id, note, created_at
FROM knowledge_endorsements WHERE artifact_id=$1 AND endorser_id=$2
`

type GetEndorsementByEndorserParams struct {
	ArtifactID uuid.UUID
	EndorserID uuid.UUID
}

func (q *Queries) GetEndorsementByEndorser(ctx context.Context, arg GetEndorsementByEndorserParams) (*KnowledgeEndorsement, error) {
	row := q.db.QueryRow(ctx, getEndorsementByEndorser, arg.ArtifactID, arg.EndorserID)
	var i KnowledgeEndorsement
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.EndorserID,
		&i.Note,
		&i.CreatedAt,
	)
	return &i, err
}

const incrementArtifactAccess = `-- name: IncrementArtifactAccess :exec
UPDATE knowledge_artifacts SET access_count=access_count+1, last_accessed=now(), updated_at=now() WHERE id=$1
`

func (q *Queries) IncrementArtifactAccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementArtifactAccess, id)
	return err
}

const incrementArtifactEndorsementCount = `-- name: IncrementArtifactEndorsementCount :exec
UPDATE knowledge_artifacts SET endorsement_count=endorsement_count+1, updated_at=now() WHERE id=$1
`

func (q *Queries) IncrementArtifactEndorsementCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementArtifactEndorsementCount, id)
	return err
}

const listAllArtifacts = `-- name: ListAllArtifacts :many
SELECT id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
FROM knowledge_artifacts
WHERE ($1::uuid = '00000000-0000-0000-0000-000000000000' OR owner_scope_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllArtifactsParams struct {
	ScopeID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAllArtifacts(ctx context.Context, arg ListAllArtifactsParams) ([]*KnowledgeArtifact, error) {
	rows, err := q.db.Query(ctx, listAllArtifacts, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeArtifact{}
	for rows.Next() {
		var i KnowledgeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByStatus = `-- name: ListArtifactsByStatus :many
SELECT id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
FROM knowledge_artifacts
WHERE status = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR owner_scope_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListArtifactsByStatusParams struct {
	Status  string
	ScopeID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListArtifactsByStatus(ctx context.Context, arg ListArtifactsByStatusParams) ([]*KnowledgeArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByStatus, arg.Status, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeArtifact{}
	for rows.Next() {
		var i KnowledgeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleArtifacts = `-- name: ListVisibleArtifacts :many
SELECT id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
FROM knowledge_artifacts
WHERE status = 'published'
  AND (owner_scope_id = ANY($1::uuid[]) OR visibility = 'company')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVisibleArtifactsParams struct {
	Column1 []uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListVisibleArtifacts(ctx context.Context, arg ListVisibleArtifactsParams) ([]*KnowledgeArtifact, error) {
	rows, err := q.db.Query(ctx, listVisibleArtifacts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeArtifact{}
	for rows.Next() {
		var i KnowledgeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nullPreviousVersionRefs = `-- name: NullPreviousVersionRefs :exec
UPDATE knowledge_artifacts SET previous_version = NULL WHERE previous_version = $1
`

func (q *Queries) NullPreviousVersionRefs(ctx context.Context, previousVersion *uuid.UUID) error {
	_, err := q.db.Exec(ctx, nullPreviousVersionRefs, previousVersion)
	return err
}

const nullPromotionRequestArtifactRef = `-- name: NullPromotionRequestArtifactRef :exec
UPDATE promotion_requests SET result_artifact_id = NULL WHERE result_artifact_id = $1
`

func (q *Queries) NullPromotionRequestArtifactRef(ctx context.Context, resultArtifactID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, nullPromotionRequestArtifactRef, resultArtifactID)
	return err
}

const recallArtifactsByFTS = `-- name: RecallArtifactsByFTS :many
WITH qs AS (SELECT path FROM scopes WHERE id = $1)
SELECT ka.id, ka.knowledge_type, ka.owner_scope_id, ka.author_id,
    ka.visibility, ka.status, ka.published_at, ka.deprecated_at, ka.review_required,
    ka.title, ka.content, ka.summary, ka.embedding, ka.embedding_model_id, ka.meta,
    ka.endorsement_count, ka.access_count, ka.last_accessed,
    ka.version, ka.previous_version, ka.source_memory_id, ka.source_ref,
    ka.created_at, ka.updated_at,
    ts_rank_cd(to_tsvector('postbrain_fts', ka.content),
               plainto_tsquery('postbrain_fts', $3)) AS bm25_score
FROM knowledge_artifacts ka
JOIN scopes s ON ka.owner_scope_id = s.id, qs
WHERE ka.status = 'published'
  AND to_tsvector('postbrain_fts', ka.content) @@ plainto_tsquery('postbrain_fts', $3)
  AND (
    (ka.visibility = 'project'    AND ka.owner_scope_id = $1)
    OR (ka.visibility IN ('team', 'department') AND s.path @> qs.path)
    OR (ka.visibility = 'company'    AND s.kind = 'company')
    OR  ka.id IN (
          SELECT sg.artifact_id FROM sharing_grants sg
          JOIN scopes gs ON sg.grantee_scope_id = gs.id
          WHERE (gs.path @> qs.path OR gs.path = qs.path)
            AND sg.artifact_id IS NOT NULL
            AND (sg.expires_at IS NULL OR sg.expires_at > now())
        )
  )
ORDER BY bm25_score DESC
LIMIT $2
`

type RecallArtifactsByFTSParams struct {
	OwnerScopeID   uuid.UUID
	Limit          int32
	PlaintoTsquery string
}

type RecallArtifactsByFTSRow struct {
	ID               uuid.UUID
	KnowledgeType    string
	OwnerScopeID     uuid.UUID
	AuthorID         uuid.UUID
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	Meta             []byte
	EndorsementCount int32
	AccessCount      int32
	LastAccessed     *time.Time
	Version          int32
	PreviousVersion  *uuid.UUID
	SourceMemoryID   *uuid.UUID
	SourceRef        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Bm25Score        float32
}

// $1 = scope_id (visibility resolution fans out automatically)
func (q *Queries) RecallArtifactsByFTS(ctx context.Context, arg RecallArtifactsByFTSParams) ([]*RecallArtifactsByFTSRow, error) {
	rows, err := q.db.Query(ctx, recallArtifactsByFTS, arg.OwnerScopeID, arg.Limit, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallArtifactsByFTSRow{}
	for rows.Next() {
		var i RecallArtifactsByFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bm25Score,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallArtifactsByTrigram = `-- name: RecallArtifactsByTrigram :many
WITH qs AS (SELECT path FROM scopes WHERE id = $1)
SELECT ka.id, ka.knowledge_type, ka.owner_scope_id, ka.author_id,
    ka.visibility, ka.status, ka.published_at, ka.deprecated_at, ka.review_required,
    ka.title, ka.content, ka.summary, ka.embedding, ka.embedding_model_id, ka.meta,
    ka.endorsement_count, ka.access_count, ka.last_accessed,
    ka.version, ka.previous_version, ka.source_memory_id, ka.source_ref,
    ka.created_at, ka.updated_at,
    similarity(ka.content, $3) AS trgm_score
FROM knowledge_artifacts ka
JOIN scopes s ON ka.owner_scope_id = s.id, qs
WHERE ka.status = 'published'
  AND similarity(ka.content, $3) > 0.1
  AND (
    (ka.visibility = 'project'    AND ka.owner_scope_id = $1)
    OR (ka.visibility IN ('team', 'department') AND s.path @> qs.path)
    OR (ka.visibility = 'company'    AND s.kind = 'company')
    OR  ka.id IN (
          SELECT sg.artifact_id FROM sharing_grants sg
          JOIN scopes gs ON sg.grantee_scope_id = gs.id
          WHERE (gs.path @> qs.path OR gs.path = qs.path)
            AND sg.artifact_id IS NOT NULL
            AND (sg.expires_at IS NULL OR sg.expires_at > now())
        )
  )
ORDER BY trgm_score DESC
LIMIT $2
`

type RecallArtifactsByTrigramParams struct {
	OwnerScopeID uuid.UUID
	Limit        int32
	Similarity   string
}

type RecallArtifactsByTrigramRow struct {
	ID               uuid.UUID
	KnowledgeType    string
	OwnerScopeID     uuid.UUID
	AuthorID         uuid.UUID
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	Meta             []byte
	EndorsementCount int32
	AccessCount      int32
	LastAccessed     *time.Time
	Version          int32
	PreviousVersion  *uuid.UUID
	SourceMemoryID   *uuid.UUID
	SourceRef        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TrgmScore        float32
}

// $1 = scope_id (visibility resolution fans out automatically)
func (q *Queries) RecallArtifactsByTrigram(ctx context.Context, arg RecallArtifactsByTrigramParams) ([]*RecallArtifactsByTrigramRow, error) {
	rows, err := q.db.Query(ctx, recallArtifactsByTrigram, arg.OwnerScopeID, arg.Limit, arg.Similarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallArtifactsByTrigramRow{}
	for rows.Next() {
		var i RecallArtifactsByTrigramRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrgmScore,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallArtifactsByVector = `-- name: RecallArtifactsByVector :many
WITH qs AS (SELECT path FROM scopes WHERE id = $1)
SELECT ka.id, ka.knowledge_type, ka.owner_scope_id, ka.author_id,
    ka.visibility, ka.status, ka.published_at, ka.deprecated_at, ka.review_required,
    ka.title, ka.content, ka.summary, ka.embedding, ka.embedding_model_id, ka.meta,
    ka.endorsement_count, ka.access_count, ka.last_accessed,
    ka.version, ka.previous_version, ka.source_memory_id, ka.source_ref,
    ka.created_at, ka.updated_at,
    (1 - (ka.embedding <=> $3))::float4 AS vec_score
FROM knowledge_artifacts ka
JOIN scopes s ON ka.owner_scope_id = s.id, qs
WHERE ka.status = 'published'
  AND (
    (ka.visibility = 'project'    AND ka.owner_scope_id = $1)
    OR (ka.visibility IN ('team', 'department') AND s.path @> qs.path)
    OR (ka.visibility = 'company'    AND s.kind = 'company')
    OR  ka.id IN (
          SELECT sg.artifact_id FROM sharing_grants sg
          JOIN scopes gs ON sg.grantee_scope_id = gs.id
          WHERE (gs.path @> qs.path OR gs.path = qs.path)
            AND sg.artifact_id IS NOT NULL
            AND (sg.expires_at IS NULL OR sg.expires_at > now())
        )
  )
ORDER BY ka.embedding <=> $3
LIMIT $2
`

type RecallArtifactsByVectorParams struct {
	OwnerScopeID uuid.UUID
	Limit        int32
	Embedding    *pgvector_go.Vector
}

type RecallArtifactsByVectorRow struct {
	ID               uuid.UUID
	KnowledgeType    string
	OwnerScopeID     uuid.UUID
	AuthorID         uuid.UUID
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	Meta             []byte
	EndorsementCount int32
	AccessCount      int32
	LastAccessed     *time.Time
	Version          int32
	PreviousVersion  *uuid.UUID
	SourceMemoryID   *uuid.UUID
	SourceRef        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	VecScore         float32
}

// $1 = scope_id (the queried scope; visibility resolution fans out automatically)
func (q *Queries) RecallArtifactsByVector(ctx context.Context, arg RecallArtifactsByVectorParams) ([]*RecallArtifactsByVectorRow, error) {
	rows, err := q.db.Query(ctx, recallArtifactsByVector, arg.OwnerScopeID, arg.Limit, arg.Embedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallArtifactsByVectorRow{}
	for rows.Next() {
		var i RecallArtifactsByVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VecScore,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPromotedMemoryStatus = `-- name: ResetPromotedMemoryStatus :exec
UPDATE memories SET promotion_status = NULL WHERE promoted_to = $1
`

func (q *Queries) ResetPromotedMemoryStatus(ctx context.Context, promotedTo *uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetPromotedMemoryStatus, promotedTo)
	return err
}

const searchArtifacts = `-- name: SearchArtifacts :many
SELECT id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
FROM knowledge_artifacts
WHERE (title ILIKE $1 OR content ILIKE $1)
  AND ($2 = '' OR status = $2)
  AND ($3::uuid = '00000000-0000-0000-0000-000000000000' OR owner_scope_id = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type SearchArtifactsParams struct {
	Title   string
	Column2 interface{}
	ScopeID uuid.UUID
	Limit   int32
	Offset  int32
}

// $1 = query (wrapped in %...% by caller), $2 = status filter (” = all), $3 = scope_id (zero = all), $4 = limit, $5 = offset
func (q *Queries) SearchArtifacts(ctx context.Context, arg SearchArtifactsParams) ([]*KnowledgeArtifact, error) {
	rows, err := q.db.Query(ctx, searchArtifacts,
		arg.Title,
		arg.Column2,
		arg.ScopeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*KnowledgeArtifact{}
	for rows.Next() {
		var i KnowledgeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeType,
			&i.OwnerScopeID,
			&i.AuthorID,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.Meta,
			&i.EndorsementCount,
			&i.AccessCount,
			&i.LastAccessed,
			&i.Version,
			&i.PreviousVersion,
			&i.SourceMemoryID,
			&i.SourceRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotArtifactVersion = `-- name: SnapshotArtifactVersion :exec
INSERT INTO knowledge_history (artifact_id, version, content, summary, changed_by, change_note)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (artifact_id, version) DO NOTHING
`

type SnapshotArtifactVersionParams struct {
	ArtifactID uuid.UUID
	Version    int32
	Content    string
	Summary    *string
	ChangedBy  uuid.UUID
	ChangeNote *string
}

func (q *Queries) SnapshotArtifactVersion(ctx context.Context, arg SnapshotArtifactVersionParams) error {
	_, err := q.db.Exec(ctx, snapshotArtifactVersion,
		arg.ArtifactID,
		arg.Version,
		arg.Content,
		arg.Summary,
		arg.ChangedBy,
		arg.ChangeNote,
	)
	return err
}

const updateArtifact = `-- name: UpdateArtifact :one
UPDATE knowledge_artifacts
SET title=$2, content=$3, summary=$4, embedding=$5,
    embedding_model_id=$6, version=version+1, updated_at=now()
WHERE id=$1
RETURNING id, knowledge_type, owner_scope_id, author_id,
    visibility, status, published_at, deprecated_at, review_required,
    title, content, summary, embedding, embedding_model_id, meta,
    endorsement_count, access_count, last_accessed,
    version, previous_version, source_memory_id, source_ref,
    created_at, updated_at
`

type UpdateArtifactParams struct {
	ID               uuid.UUID
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (*KnowledgeArtifact, error) {
	row := q.db.QueryRow(ctx, updateArtifact,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Embedding,
		arg.EmbeddingModelID,
	)
	var i KnowledgeArtifact
	err := row.Scan(
		&i.ID,
		&i.KnowledgeType,
		&i.OwnerScopeID,
		&i.AuthorID,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.Meta,
		&i.EndorsementCount,
		&i.AccessCount,
		&i.LastAccessed,
		&i.Version,
		&i.PreviousVersion,
		&i.SourceMemoryID,
		&i.SourceRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateArtifactStatus = `-- name: UpdateArtifactStatus :exec
UPDATE knowledge_artifacts
SET status=$2, published_at=$3, deprecated_at=$4, updated_at=now()
WHERE id=$1
`

type UpdateArtifactStatusParams struct {
	ID           uuid.UUID
	Status       string
	PublishedAt  *time.Time
	DeprecatedAt *time.Time
}

func (q *Queries) UpdateArtifactStatus(ctx context.Context, arg UpdateArtifactStatusParams) error {
	_, err := q.db.Exec(ctx, updateArtifactStatus,
		arg.ID,
		arg.Status,
		arg.PublishedAt,
		arg.DeprecatedAt,
	)
	return err
}
