// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO principal_memberships (member_id, parent_id, role, granted_by)
VALUES ($1, $2, $3, $4)
RETURNING member_id, parent_id, role, granted_by, created_at
`

type CreateMembershipParams struct {
	MemberID  uuid.UUID
	ParentID  uuid.UUID
	Role      string
	GrantedBy uuid.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (*PrincipalMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.MemberID,
		arg.ParentID,
		arg.Role,
		arg.GrantedBy,
	)
	var i PrincipalMembership
	err := row.Scan(
		&i.MemberID,
		&i.ParentID,
		&i.Role,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM principal_memberships WHERE member_id = $1 AND parent_id = $2
`

type DeleteMembershipParams struct {
	MemberID uuid.UUID
	ParentID uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.MemberID, arg.ParentID)
	return err
}

const getAllParentIDs = `-- name: GetAllParentIDs :many
WITH RECURSIVE member_tree AS (
    SELECT $1::uuid AS id
    UNION ALL
    SELECT pm.parent_id
    FROM   principal_memberships pm
    JOIN   member_tree mt ON pm.member_id = mt.id
)
SELECT id FROM member_tree
`

func (q *Queries) GetAllParentIDs(ctx context.Context, dollar_1 uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAllParentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberships = `-- name: GetMemberships :many
SELECT member_id, parent_id, role, granted_by, created_at
FROM principal_memberships WHERE member_id = $1
`

func (q *Queries) GetMemberships(ctx context.Context, memberID uuid.UUID) ([]*PrincipalMembership, error) {
	rows, err := q.db.Query(ctx, getMemberships, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PrincipalMembership{}
	for rows.Next() {
		var i PrincipalMembership
		if err := rows.Scan(
			&i.MemberID,
			&i.ParentID,
			&i.Role,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
