// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories
(memory_type, scope_id, author_id, content, summary,
 embedding, embedding_model_id, embedding_code, embedding_code_model_id,
 content_kind, meta, version, is_active, confidence, importance,
 access_count, expires_at, promotion_status, promoted_to, source_ref, parent_memory_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,
        COALESCE($12,1),true,COALESCE($13,1.0),COALESCE($14,0.5),
        0,$15,$16,$17,$18,$19)
RETURNING id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
`

type CreateMemoryParams struct {
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Column12             interface{}
	Column13             interface{}
	Column14             interface{}
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
}

type CreateMemoryRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (*CreateMemoryRow, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.MemoryType,
		arg.ScopeID,
		arg.AuthorID,
		arg.Content,
		arg.Summary,
		arg.Embedding,
		arg.EmbeddingModelID,
		arg.EmbeddingCode,
		arg.EmbeddingCodeModelID,
		arg.ContentKind,
		arg.Meta,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.ExpiresAt,
		arg.PromotionStatus,
		arg.PromotedTo,
		arg.SourceRef,
		arg.ParentMemoryID,
	)
	var i CreateMemoryRow
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.ScopeID,
		&i.AuthorID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.EmbeddingCode,
		&i.EmbeddingCodeModelID,
		&i.ContentKind,
		&i.Meta,
		&i.Version,
		&i.IsActive,
		&i.Confidence,
		&i.Importance,
		&i.AccessCount,
		&i.LastAccessed,
		&i.ExpiresAt,
		&i.PromotionStatus,
		&i.PromotedTo,
		&i.SourceRef,
		&i.ParentMemoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findNearDuplicates = `-- name: FindNearDuplicates :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
FROM memories
WHERE scope_id = $1
  AND is_active = true
  AND (embedding <=> $2) <= $3::float8
  AND ($4::uuid IS NULL OR id != $4)
LIMIT 5
`

type FindNearDuplicatesParams struct {
	ScopeID   uuid.UUID
	Embedding *pgvector_go.Vector
	Column3   float64
	Column4   uuid.UUID
}

type FindNearDuplicatesRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) FindNearDuplicates(ctx context.Context, arg FindNearDuplicatesParams) ([]*FindNearDuplicatesRow, error) {
	rows, err := q.db.Query(ctx, findNearDuplicates,
		arg.ScopeID,
		arg.Embedding,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindNearDuplicatesRow{}
	for rows.Next() {
		var i FindNearDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemory = `-- name: GetMemory :one
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
FROM memories WHERE id = $1
`

type GetMemoryRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetMemory(ctx context.Context, id uuid.UUID) (*GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.ScopeID,
		&i.AuthorID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.EmbeddingCode,
		&i.EmbeddingCodeModelID,
		&i.ContentKind,
		&i.Meta,
		&i.Version,
		&i.IsActive,
		&i.Confidence,
		&i.Importance,
		&i.AccessCount,
		&i.LastAccessed,
		&i.ExpiresAt,
		&i.PromotionStatus,
		&i.PromotedTo,
		&i.SourceRef,
		&i.ParentMemoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const hardDeleteMemory = `-- name: HardDeleteMemory :exec
DELETE FROM memories WHERE id=$1
`

func (q *Queries) HardDeleteMemory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteMemory, id)
	return err
}

const incrementMemoryAccess = `-- name: IncrementMemoryAccess :exec
UPDATE memories SET access_count=access_count+1, last_accessed=now(), updated_at=now() WHERE id=$1
`

func (q *Queries) IncrementMemoryAccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMemoryAccess, id)
	return err
}

const listChunkMemories = `-- name: ListChunkMemories :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
FROM memories
WHERE parent_memory_id = $1 AND is_active = true
ORDER BY created_at
`

type ListChunkMemoriesRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Returns chunk memories (children) for a given parent memory.
func (q *Queries) ListChunkMemories(ctx context.Context, parentMemoryID *uuid.UUID) ([]*ListChunkMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listChunkMemories, parentMemoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListChunkMemoriesRow{}
	for rows.Next() {
		var i ListChunkMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsolidationCandidates = `-- name: ListConsolidationCandidates :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
FROM memories
WHERE is_active = true AND scope_id = $1 AND importance < 0.7 AND access_count < 3
`

type ListConsolidationCandidatesRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) ListConsolidationCandidates(ctx context.Context, scopeID uuid.UUID) ([]*ListConsolidationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listConsolidationCandidates, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListConsolidationCandidatesRow{}
	for rows.Next() {
		var i ListConsolidationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByScope = `-- name: ListMemoriesByScope :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
FROM memories WHERE scope_id=$1 AND is_active=true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMemoriesByScopeParams struct {
	ScopeID uuid.UUID
	Limit   int32
	Offset  int32
}

type ListMemoriesByScopeRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) ListMemoriesByScope(ctx context.Context, arg ListMemoriesByScopeParams) ([]*ListMemoriesByScopeRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesByScope, arg.ScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMemoriesByScopeRow{}
	for rows.Next() {
		var i ListMemoriesByScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesForEntity = `-- name: ListMemoriesForEntity :many
SELECT m.id, m.memory_type, m.scope_id, m.author_id,
    m.content, m.summary, m.embedding, m.embedding_model_id,
    m.embedding_code, m.embedding_code_model_id, m.content_kind, m.meta,
    m.version, m.is_active, m.confidence, m.importance, m.access_count, m.last_accessed,
    m.expires_at, m.promotion_status, m.promoted_to, m.source_ref, m.parent_memory_id, m.created_at, m.updated_at
FROM memories m
JOIN memory_entities me ON me.memory_id = m.id
WHERE me.entity_id = $1 AND m.is_active = true
ORDER BY m.created_at DESC
LIMIT $2
`

type ListMemoriesForEntityParams struct {
	EntityID uuid.UUID
	Limit    int32
}

type ListMemoriesForEntityRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Returns active memories linked to a given entity, most recent first.
func (q *Queries) ListMemoriesForEntity(ctx context.Context, arg ListMemoriesForEntityParams) ([]*ListMemoriesForEntityRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesForEntity, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMemoriesForEntityRow{}
	for rows.Next() {
		var i ListMemoriesForEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMemoriesByCodeVector = `-- name: RecallMemoriesByCodeVector :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at,
    (1 - (embedding_code <=> $3))::float4 AS vec_score
FROM memories
WHERE is_active = true AND scope_id = ANY($1::uuid[]) AND embedding_code IS NOT NULL
  AND created_at >= $4::timestamptz
  AND created_at <= $5::timestamptz
ORDER BY embedding_code <=> $3
LIMIT $2
`

type RecallMemoriesByCodeVectorParams struct {
	Column1       []uuid.UUID
	Limit         int32
	EmbeddingCode *pgvector_go.Vector
	Column4       time.Time
	Column5       time.Time
}

type RecallMemoriesByCodeVectorRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	VecScore             float32
}

func (q *Queries) RecallMemoriesByCodeVector(ctx context.Context, arg RecallMemoriesByCodeVectorParams) ([]*RecallMemoriesByCodeVectorRow, error) {
	rows, err := q.db.Query(ctx, recallMemoriesByCodeVector,
		arg.Column1,
		arg.Limit,
		arg.EmbeddingCode,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallMemoriesByCodeVectorRow{}
	for rows.Next() {
		var i RecallMemoriesByCodeVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VecScore,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMemoriesByFTS = `-- name: RecallMemoriesByFTS :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at,
    ts_rank_cd(to_tsvector('postbrain_fts', content), plainto_tsquery('postbrain_fts', $3)) AS bm25_score
FROM memories
WHERE is_active = true AND scope_id = ANY($1::uuid[])
  AND created_at >= $4::timestamptz
  AND created_at <= $5::timestamptz
  AND to_tsvector('postbrain_fts', content) @@ plainto_tsquery('postbrain_fts', $3)
ORDER BY bm25_score DESC
LIMIT $2
`

type RecallMemoriesByFTSParams struct {
	Column1        []uuid.UUID
	Limit          int32
	PlaintoTsquery string
	Column4        time.Time
	Column5        time.Time
}

type RecallMemoriesByFTSRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Bm25Score            float32
}

func (q *Queries) RecallMemoriesByFTS(ctx context.Context, arg RecallMemoriesByFTSParams) ([]*RecallMemoriesByFTSRow, error) {
	rows, err := q.db.Query(ctx, recallMemoriesByFTS,
		arg.Column1,
		arg.Limit,
		arg.PlaintoTsquery,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallMemoriesByFTSRow{}
	for rows.Next() {
		var i RecallMemoriesByFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bm25Score,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMemoriesByTrigram = `-- name: RecallMemoriesByTrigram :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at,
    similarity(content, $3) AS trgm_score
FROM memories
WHERE is_active = true AND scope_id = ANY($1::uuid[])
  AND created_at >= $4::timestamptz
  AND created_at <= $5::timestamptz
  AND similarity(content, $3) > 0.1
ORDER BY trgm_score DESC
LIMIT $2
`

type RecallMemoriesByTrigramParams struct {
	Column1    []uuid.UUID
	Limit      int32
	Similarity string
	Column4    time.Time
	Column5    time.Time
}

type RecallMemoriesByTrigramRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TrgmScore            float32
}

func (q *Queries) RecallMemoriesByTrigram(ctx context.Context, arg RecallMemoriesByTrigramParams) ([]*RecallMemoriesByTrigramRow, error) {
	rows, err := q.db.Query(ctx, recallMemoriesByTrigram,
		arg.Column1,
		arg.Limit,
		arg.Similarity,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallMemoriesByTrigramRow{}
	for rows.Next() {
		var i RecallMemoriesByTrigramRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrgmScore,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMemoriesByVector = `-- name: RecallMemoriesByVector :many
SELECT id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at,
    (1 - (embedding <=> $3))::float4 AS vec_score
FROM memories
WHERE is_active = true AND scope_id = ANY($1::uuid[])
  AND created_at >= $4::timestamptz
  AND created_at <= $5::timestamptz
ORDER BY embedding <=> $3
LIMIT $2
`

type RecallMemoriesByVectorParams struct {
	Column1   []uuid.UUID
	Limit     int32
	Embedding *pgvector_go.Vector
	Column4   time.Time
	Column5   time.Time
}

type RecallMemoriesByVectorRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	VecScore             float32
}

func (q *Queries) RecallMemoriesByVector(ctx context.Context, arg RecallMemoriesByVectorParams) ([]*RecallMemoriesByVectorRow, error) {
	rows, err := q.db.Query(ctx, recallMemoriesByVector,
		arg.Column1,
		arg.Limit,
		arg.Embedding,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallMemoriesByVectorRow{}
	for rows.Next() {
		var i RecallMemoriesByVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryType,
			&i.ScopeID,
			&i.AuthorID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.EmbeddingCode,
			&i.EmbeddingCodeModelID,
			&i.ContentKind,
			&i.Meta,
			&i.Version,
			&i.IsActive,
			&i.Confidence,
			&i.Importance,
			&i.AccessCount,
			&i.LastAccessed,
			&i.ExpiresAt,
			&i.PromotionStatus,
			&i.PromotedTo,
			&i.SourceRef,
			&i.ParentMemoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VecScore,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemory = `-- name: SoftDeleteMemory :exec
UPDATE memories SET is_active=false, updated_at=now() WHERE id=$1
`

func (q *Queries) SoftDeleteMemory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMemory, id)
	return err
}

const updateMemoryContent = `-- name: UpdateMemoryContent :one
UPDATE memories
SET content=$2, embedding=$3, embedding_model_id=$4,
    embedding_code=$5, embedding_code_model_id=$6,
    content_kind=$7, summary=$8, meta=$9, version=version+1, updated_at=now()
WHERE id=$1
RETURNING id, memory_type, scope_id, author_id,
    content, summary, embedding, embedding_model_id,
    embedding_code, embedding_code_model_id, content_kind, meta,
    version, is_active, confidence, importance, access_count, last_accessed,
    expires_at, promotion_status, promoted_to, source_ref, parent_memory_id, created_at, updated_at
`

type UpdateMemoryContentParams struct {
	ID                   uuid.UUID
	Content              string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Summary              *string
	Meta                 []byte
}

type UpdateMemoryContentRow struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	ParentMemoryID       *uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) UpdateMemoryContent(ctx context.Context, arg UpdateMemoryContentParams) (*UpdateMemoryContentRow, error) {
	row := q.db.QueryRow(ctx, updateMemoryContent,
		arg.ID,
		arg.Content,
		arg.Embedding,
		arg.EmbeddingModelID,
		arg.EmbeddingCode,
		arg.EmbeddingCodeModelID,
		arg.ContentKind,
		arg.Summary,
		arg.Meta,
	)
	var i UpdateMemoryContentRow
	err := row.Scan(
		&i.ID,
		&i.MemoryType,
		&i.ScopeID,
		&i.AuthorID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.EmbeddingCode,
		&i.EmbeddingCodeModelID,
		&i.ContentKind,
		&i.Meta,
		&i.Version,
		&i.IsActive,
		&i.Confidence,
		&i.Importance,
		&i.AccessCount,
		&i.LastAccessed,
		&i.ExpiresAt,
		&i.PromotionStatus,
		&i.PromotedTo,
		&i.SourceRef,
		&i.ParentMemoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
