// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type ArtifactDigestSource struct {
	DigestID uuid.UUID
	SourceID uuid.UUID
	AddedAt  time.Time
}

type ArtifactEntity struct {
	ArtifactID uuid.UUID
	EntityID   uuid.UUID
	Role       *string
}

type Consolidation struct {
	ID        uuid.UUID
	ScopeID   uuid.UUID
	SourceIds []uuid.UUID
	ResultID  *uuid.UUID
	Strategy  string
	Reason    *string
	CreatedAt time.Time
}

type EmbeddingModel struct {
	ID          uuid.UUID
	Slug        string
	Dimensions  int32
	ContentType string
	IsActive    bool
	Description *string
	CreatedAt   time.Time
}

type Entity struct {
	ID               uuid.UUID
	ScopeID          uuid.UUID
	EntityType       string
	Name             string
	Canonical        string
	Meta             []byte
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Event struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	ScopeID   uuid.UUID
	EventType string
	Payload   []byte
	CreatedAt time.Time
}

type KnowledgeArtifact struct {
	ID               uuid.UUID
	KnowledgeType    string
	OwnerScopeID     uuid.UUID
	AuthorID         uuid.UUID
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Title            string
	Content          string
	Summary          *string
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	Meta             []byte
	EndorsementCount int32
	AccessCount      int32
	LastAccessed     *time.Time
	Version          int32
	PreviousVersion  *uuid.UUID
	SourceMemoryID   *uuid.UUID
	SourceRef        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type KnowledgeCollection struct {
	ID          uuid.UUID
	ScopeID     uuid.UUID
	OwnerID     uuid.UUID
	Slug        string
	Name        string
	Description *string
	Visibility  string
	Meta        []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type KnowledgeCollectionItem struct {
	CollectionID uuid.UUID
	ArtifactID   uuid.UUID
	Position     int32
	AddedBy      uuid.UUID
	AddedAt      time.Time
}

type KnowledgeDigestLog struct {
	ID            uuid.UUID
	ScopeID       uuid.UUID
	DigestID      uuid.UUID
	SourceIds     []uuid.UUID
	Strategy      string
	SynthesisedBy *uuid.UUID
	CreatedAt     time.Time
}

type KnowledgeEndorsement struct {
	ID         uuid.UUID
	ArtifactID uuid.UUID
	EndorserID uuid.UUID
	Note       *string
	CreatedAt  time.Time
}

type KnowledgeHistory struct {
	ID         uuid.UUID
	ArtifactID uuid.UUID
	Version    int32
	Content    string
	Summary    *string
	ChangedBy  uuid.UUID
	ChangeNote *string
	CreatedAt  time.Time
}

type Memory struct {
	ID                   uuid.UUID
	MemoryType           string
	ScopeID              uuid.UUID
	AuthorID             uuid.UUID
	Content              string
	Summary              *string
	Embedding            *pgvector_go.Vector
	EmbeddingModelID     *uuid.UUID
	EmbeddingCode        *pgvector_go.Vector
	EmbeddingCodeModelID *uuid.UUID
	ContentKind          string
	Meta                 []byte
	Version              int32
	IsActive             bool
	Confidence           float64
	Importance           float64
	AccessCount          int32
	LastAccessed         *time.Time
	ExpiresAt            *time.Time
	PromotionStatus      string
	PromotedTo           *uuid.UUID
	SourceRef            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ParentMemoryID       *uuid.UUID
}

type MemoryEntity struct {
	MemoryID uuid.UUID
	EntityID uuid.UUID
	Role     *string
}

type Principal struct {
	ID          uuid.UUID
	Kind        string
	Slug        string
	DisplayName string
	Meta        []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PrincipalMembership struct {
	MemberID  uuid.UUID
	ParentID  uuid.UUID
	Role      string
	GrantedBy *uuid.UUID
	CreatedAt time.Time
}

type PromotionRequest struct {
	ID                   uuid.UUID
	MemoryID             uuid.UUID
	RequestedBy          uuid.UUID
	TargetScopeID        uuid.UUID
	TargetVisibility     string
	ProposedTitle        *string
	ProposedCollectionID *uuid.UUID
	Status               string
	ReviewerID           *uuid.UUID
	ReviewNote           *string
	ReviewedAt           *time.Time
	ResultArtifactID     *uuid.UUID
	CreatedAt            time.Time
}

type Relation struct {
	ID             uuid.UUID
	ScopeID        uuid.UUID
	SubjectID      uuid.UUID
	Predicate      string
	ObjectID       uuid.UUID
	Confidence     float64
	SourceMemory   *uuid.UUID
	CreatedAt      time.Time
	SourceArtifact *uuid.UUID
	SourceFile     *string
}

type Scope struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	CreatedAt         time.Time
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
}

type Session struct {
	ID          uuid.UUID
	ScopeID     uuid.UUID
	PrincipalID *uuid.UUID
	StartedAt   time.Time
	EndedAt     *time.Time
	Meta        []byte
}

type SharingGrant struct {
	ID             uuid.UUID
	MemoryID       *uuid.UUID
	ArtifactID     *uuid.UUID
	GranteeScopeID uuid.UUID
	GrantedBy      uuid.UUID
	CanReshare     bool
	ExpiresAt      *time.Time
	CreatedAt      time.Time
}

type Skill struct {
	ID               uuid.UUID
	ScopeID          uuid.UUID
	AuthorID         uuid.UUID
	SourceArtifactID *uuid.UUID
	Slug             string
	Name             string
	Description      string
	AgentTypes       []string
	Body             string
	Parameters       []byte
	Visibility       string
	Status           string
	PublishedAt      *time.Time
	DeprecatedAt     *time.Time
	ReviewRequired   int32
	Version          int32
	PreviousVersion  *uuid.UUID
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
	InvocationCount  int32
	LastInvokedAt    *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SkillEndorsement struct {
	ID         uuid.UUID
	SkillID    uuid.UUID
	EndorserID uuid.UUID
	Note       *string
	CreatedAt  time.Time
}

type SkillHistory struct {
	ID         uuid.UUID
	SkillID    uuid.UUID
	Version    int32
	Body       string
	Parameters []byte
	ChangedBy  uuid.UUID
	ChangeNote *string
	CreatedAt  time.Time
}

type StalenessFlag struct {
	ID         uuid.UUID
	ArtifactID uuid.UUID
	Signal     string
	Confidence float64
	Evidence   []byte
	Status     string
	FlaggedAt  time.Time
	ReviewedBy *uuid.UUID
	ReviewedAt *time.Time
	ReviewNote *string
}

type Token struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	TokenHash   string
	Name        string
	ScopeIds    []uuid.UUID
	Permissions []string
	ExpiresAt   *time.Time
	LastUsedAt  *time.Time
	CreatedAt   time.Time
	RevokedAt   *time.Time
}
