// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_codes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeCode = `-- name: ConsumeCode :one
UPDATE oauth_auth_codes
SET used_at = now()
WHERE code_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, code_hash, client_id, principal_id, redirect_uri, scopes, code_challenge, expires_at, used_at, created_at
`

func (q *Queries) ConsumeCode(ctx context.Context, codeHash string) (*OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, consumeCode, codeHash)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.PrincipalID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getCodeByHash = `-- name: GetCodeByHash :one
SELECT id, code_hash, client_id, principal_id, redirect_uri, scopes, code_challenge, expires_at, used_at, created_at
FROM oauth_auth_codes
WHERE code_hash = $1
`

func (q *Queries) GetCodeByHash(ctx context.Context, codeHash string) (*OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, getCodeByHash, codeHash)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.PrincipalID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const issueCode = `-- name: IssueCode :one
INSERT INTO oauth_auth_codes (
    code_hash,
    client_id,
    principal_id,
    redirect_uri,
    scopes,
    code_challenge,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code_hash, client_id, principal_id, redirect_uri, scopes, code_challenge, expires_at, used_at, created_at
`

type IssueCodeParams struct {
	CodeHash      string
	ClientID      uuid.UUID
	PrincipalID   uuid.UUID
	RedirectUri   string
	Scopes        []string
	CodeChallenge string
	ExpiresAt     time.Time
}

func (q *Queries) IssueCode(ctx context.Context, arg IssueCodeParams) (*OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, issueCode,
		arg.CodeHash,
		arg.ClientID,
		arg.PrincipalID,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.PrincipalID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}
