// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_clients.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const lookupClient = `-- name: LookupClient :one
SELECT id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_public, meta, created_at, revoked_at
FROM oauth_clients
WHERE client_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) LookupClient(ctx context.Context, clientID string) (*OauthClient, error) {
	row := q.db.QueryRow(ctx, lookupClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.IsPublic,
		&i.Meta,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const registerClient = `-- name: RegisterClient :one
INSERT INTO oauth_clients (
    client_id,
    client_secret_hash,
    name,
    redirect_uris,
    grant_types,
    scopes,
    is_public,
    meta
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_public, meta, created_at, revoked_at
`

type RegisterClientParams struct {
	ClientID         string
	ClientSecretHash *string
	Name             string
	RedirectUris     []string
	GrantTypes       []string
	Scopes           []string
	IsPublic         bool
	Meta             []byte
}

func (q *Queries) RegisterClient(ctx context.Context, arg RegisterClientParams) (*OauthClient, error) {
	row := q.db.QueryRow(ctx, registerClient,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Name,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.IsPublic,
		arg.Meta,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.IsPublic,
		&i.Meta,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const revokeClient = `-- name: RevokeClient :exec
UPDATE oauth_clients
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeClient, id)
	return err
}
