// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package db

import (
	"context"
	"time"
)

const consumeState = `-- name: ConsumeState :one
UPDATE oauth_states
SET used_at = now()
WHERE state_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, state_hash, kind, payload, expires_at, used_at, created_at
`

func (q *Queries) ConsumeState(ctx context.Context, stateHash string) (*OauthState, error) {
	row := q.db.QueryRow(ctx, consumeState, stateHash)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Kind,
		&i.Payload,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getStateByHash = `-- name: GetStateByHash :one
SELECT id, state_hash, kind, payload, expires_at, used_at, created_at
FROM oauth_states
WHERE state_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetStateByHash(ctx context.Context, stateHash string) (*OauthState, error) {
	row := q.db.QueryRow(ctx, getStateByHash, stateHash)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Kind,
		&i.Payload,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const issueState = `-- name: IssueState :one
INSERT INTO oauth_states (
    state_hash,
    kind,
    payload,
    expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, state_hash, kind, payload, expires_at, used_at, created_at
`

type IssueStateParams struct {
	StateHash string
	Kind      string
	Payload   []byte
	ExpiresAt time.Time
}

func (q *Queries) IssueState(ctx context.Context, arg IssueStateParams) (*OauthState, error) {
	row := q.db.QueryRow(ctx, issueState,
		arg.StateHash,
		arg.Kind,
		arg.Payload,
		arg.ExpiresAt,
	)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Kind,
		&i.Payload,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}
