// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: principals.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO principals (kind, slug, display_name, meta)
VALUES ($1, $2, $3, $4)
RETURNING id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
`

type CreatePrincipalParams struct {
	Kind        string
	Slug        string
	DisplayName string
	Meta        []byte
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (*Principal, error) {
	row := q.db.QueryRow(ctx, createPrincipal,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Meta,
	)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSystemAdmin,
	)
	return &i, err
}

const deletePrincipal = `-- name: DeletePrincipal :exec
DELETE FROM principals WHERE id = $1
`

func (q *Queries) DeletePrincipal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrincipal, id)
	return err
}

const getPrincipalByID = `-- name: GetPrincipalByID :one
SELECT id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
FROM principals WHERE id = $1
`

func (q *Queries) GetPrincipalByID(ctx context.Context, id uuid.UUID) (*Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByID, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSystemAdmin,
	)
	return &i, err
}

const getPrincipalBySlug = `-- name: GetPrincipalBySlug :one
SELECT id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
FROM principals WHERE slug = $1
`

func (q *Queries) GetPrincipalBySlug(ctx context.Context, slug string) (*Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalBySlug, slug)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSystemAdmin,
	)
	return &i, err
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
FROM principals
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPrincipalsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPrincipals(ctx context.Context, arg ListPrincipalsParams) ([]*Principal, error) {
	rows, err := q.db.Query(ctx, listPrincipals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSystemAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSystemAdmin = `-- name: SetSystemAdmin :exec
UPDATE principals SET is_system_admin = $2, updated_at = now()
WHERE id = $1
`

type SetSystemAdminParams struct {
	ID            uuid.UUID
	IsSystemAdmin bool
}

func (q *Queries) SetSystemAdmin(ctx context.Context, arg SetSystemAdminParams) error {
	_, err := q.db.Exec(ctx, setSystemAdmin, arg.ID, arg.IsSystemAdmin)
	return err
}

const updatePrincipal = `-- name: UpdatePrincipal :one
UPDATE principals SET display_name=$2, meta=$3, updated_at=now()
WHERE id=$1
RETURNING id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
`

type UpdatePrincipalParams struct {
	ID          uuid.UUID
	DisplayName string
	Meta        []byte
}

func (q *Queries) UpdatePrincipal(ctx context.Context, arg UpdatePrincipalParams) (*Principal, error) {
	row := q.db.QueryRow(ctx, updatePrincipal, arg.ID, arg.DisplayName, arg.Meta)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSystemAdmin,
	)
	return &i, err
}

const updatePrincipalProfile = `-- name: UpdatePrincipalProfile :one
UPDATE principals SET slug=$2, display_name=$3, updated_at=now()
WHERE id=$1
RETURNING id, kind, slug, display_name, meta, created_at, updated_at, is_system_admin
`

type UpdatePrincipalProfileParams struct {
	ID          uuid.UUID
	Slug        string
	DisplayName string
}

func (q *Queries) UpdatePrincipalProfile(ctx context.Context, arg UpdatePrincipalProfileParams) (*Principal, error) {
	row := q.db.QueryRow(ctx, updatePrincipalProfile, arg.ID, arg.Slug, arg.DisplayName)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSystemAdmin,
	)
	return &i, err
}
