// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promotions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPromotionRequest = `-- name: CreatePromotionRequest :one
INSERT INTO promotion_requests
(memory_id, requested_by, target_scope_id, target_visibility,
 proposed_title, proposed_collection_id)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, memory_id, requested_by, target_scope_id, target_visibility,
    proposed_title, proposed_collection_id, status, reviewer_id, review_note,
    reviewed_at, result_artifact_id, created_at
`

type CreatePromotionRequestParams struct {
	MemoryID             uuid.UUID
	RequestedBy          uuid.UUID
	TargetScopeID        uuid.UUID
	TargetVisibility     string
	ProposedTitle        *string
	ProposedCollectionID *uuid.UUID
}

func (q *Queries) CreatePromotionRequest(ctx context.Context, arg CreatePromotionRequestParams) (*PromotionRequest, error) {
	row := q.db.QueryRow(ctx, createPromotionRequest,
		arg.MemoryID,
		arg.RequestedBy,
		arg.TargetScopeID,
		arg.TargetVisibility,
		arg.ProposedTitle,
		arg.ProposedCollectionID,
	)
	var i PromotionRequest
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.RequestedBy,
		&i.TargetScopeID,
		&i.TargetVisibility,
		&i.ProposedTitle,
		&i.ProposedCollectionID,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ResultArtifactID,
		&i.CreatedAt,
	)
	return &i, err
}

const getPromotionRequest = `-- name: GetPromotionRequest :one
SELECT id, memory_id, requested_by, target_scope_id, target_visibility,
    proposed_title, proposed_collection_id, status, reviewer_id, review_note,
    reviewed_at, result_artifact_id, created_at
FROM promotion_requests WHERE id=$1
`

func (q *Queries) GetPromotionRequest(ctx context.Context, id uuid.UUID) (*PromotionRequest, error) {
	row := q.db.QueryRow(ctx, getPromotionRequest, id)
	var i PromotionRequest
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.RequestedBy,
		&i.TargetScopeID,
		&i.TargetVisibility,
		&i.ProposedTitle,
		&i.ProposedCollectionID,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.ResultArtifactID,
		&i.CreatedAt,
	)
	return &i, err
}

const listPendingPromotions = `-- name: ListPendingPromotions :many
SELECT id, memory_id, requested_by, target_scope_id, target_visibility,
    proposed_title, proposed_collection_id, status, reviewer_id, review_note,
    reviewed_at, result_artifact_id, created_at
FROM promotion_requests
WHERE status='pending' AND target_scope_id=$1
ORDER BY created_at
`

func (q *Queries) ListPendingPromotions(ctx context.Context, targetScopeID uuid.UUID) ([]*PromotionRequest, error) {
	rows, err := q.db.Query(ctx, listPendingPromotions, targetScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PromotionRequest{}
	for rows.Next() {
		var i PromotionRequest
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.RequestedBy,
			&i.TargetScopeID,
			&i.TargetVisibility,
			&i.ProposedTitle,
			&i.ProposedCollectionID,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.ResultArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromotionRequest = `-- name: UpdatePromotionRequest :exec
UPDATE promotion_requests
SET status=$2, reviewer_id=$3, review_note=$4, reviewed_at=now(), result_artifact_id=$5
WHERE id=$1
`

type UpdatePromotionRequestParams struct {
	ID               uuid.UUID
	Status           string
	ReviewerID       *uuid.UUID
	ReviewNote       *string
	ResultArtifactID *uuid.UUID
}

func (q *Queries) UpdatePromotionRequest(ctx context.Context, arg UpdatePromotionRequestParams) error {
	_, err := q.db.Exec(ctx, updatePromotionRequest,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.ResultArtifactID,
	)
	return err
}
