// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reembed.sql

package db

import (
	"context"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const getArtifactOwnerScopeID = `-- name: GetArtifactOwnerScopeID :one
SELECT owner_scope_id FROM knowledge_artifacts WHERE id = $1
`

func (q *Queries) GetArtifactOwnerScopeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getArtifactOwnerScopeID, id)
	var owner_scope_id uuid.UUID
	err := row.Scan(&owner_scope_id)
	return owner_scope_id, err
}

const getMemoryScopeID = `-- name: GetMemoryScopeID :one
SELECT scope_id FROM memories WHERE id = $1
`

func (q *Queries) GetMemoryScopeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getMemoryScopeID, id)
	var scope_id uuid.UUID
	err := row.Scan(&scope_id)
	return scope_id, err
}

const getPendingCodeEmbeddingBatch = `-- name: GetPendingCodeEmbeddingBatch :many
SELECT ei.object_id, ei.retry_count, m.content, m.scope_id
FROM embedding_index ei
JOIN memories m ON ei.object_type='memory' AND m.id=ei.object_id
WHERE ei.model_id = $1
  AND ei.status = 'pending'
  AND m.is_active = true
  AND m.content_kind = 'code'
ORDER BY ei.updated_at, ei.object_id
LIMIT $2
`

type GetPendingCodeEmbeddingBatchParams struct {
	ModelID uuid.UUID
	Limit   int32
}

type GetPendingCodeEmbeddingBatchRow struct {
	ObjectID   uuid.UUID
	RetryCount int32
	Content    string
	ScopeID    uuid.UUID
}

func (q *Queries) GetPendingCodeEmbeddingBatch(ctx context.Context, arg GetPendingCodeEmbeddingBatchParams) ([]*GetPendingCodeEmbeddingBatchRow, error) {
	rows, err := q.db.Query(ctx, getPendingCodeEmbeddingBatch, arg.ModelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPendingCodeEmbeddingBatchRow{}
	for rows.Next() {
		var i GetPendingCodeEmbeddingBatchRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.RetryCount,
			&i.Content,
			&i.ScopeID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTextEmbeddingBatch = `-- name: GetPendingTextEmbeddingBatch :many
SELECT ei.object_type, ei.object_id, ei.retry_count,
       COALESCE(
           CASE
               WHEN ei.object_type='skill' THEN btrim(concat_ws(' ', NULLIF(s.description, ''), NULLIF(s.body, '')))
               ELSE COALESCE(m.content, ka.content, s.body)
           END,
           ''::text
       ) AS content
FROM embedding_index ei
LEFT JOIN memories m ON ei.object_type='memory' AND m.id=ei.object_id AND m.is_active=true
LEFT JOIN knowledge_artifacts ka ON ei.object_type='knowledge_artifact' AND ka.id=ei.object_id
LEFT JOIN skills s ON ei.object_type='skill' AND s.id=ei.object_id
WHERE ei.model_id = $1
  AND ei.status = 'pending'
  AND ei.object_type IN ('memory','knowledge_artifact','skill')
ORDER BY ei.updated_at, ei.object_id
LIMIT $2
`

type GetPendingTextEmbeddingBatchParams struct {
	ModelID uuid.UUID
	Limit   int32
}

type GetPendingTextEmbeddingBatchRow struct {
	ObjectType string
	ObjectID   uuid.UUID
	RetryCount int32
	Content    interface{}
}

func (q *Queries) GetPendingTextEmbeddingBatch(ctx context.Context, arg GetPendingTextEmbeddingBatchParams) ([]*GetPendingTextEmbeddingBatchRow, error) {
	rows, err := q.db.Query(ctx, getPendingTextEmbeddingBatch, arg.ModelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPendingTextEmbeddingBatchRow{}
	for rows.Next() {
		var i GetPendingTextEmbeddingBatchRow
		if err := rows.Scan(
			&i.ObjectType,
			&i.ObjectID,
			&i.RetryCount,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillScopeID = `-- name: GetSkillScopeID :one
SELECT scope_id FROM skills WHERE id = $1
`

func (q *Queries) GetSkillScopeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSkillScopeID, id)
	var scope_id uuid.UUID
	err := row.Scan(&scope_id)
	return scope_id, err
}

const markEmbeddingIndexFailed = `-- name: MarkEmbeddingIndexFailed :exec
UPDATE embedding_index
SET status=$4, retry_count=$5, last_error=$6, updated_at=now()
WHERE object_type=$1 AND object_id=$2 AND model_id=$3
`

type MarkEmbeddingIndexFailedParams struct {
	ObjectType string
	ObjectID   uuid.UUID
	ModelID    uuid.UUID
	Status     string
	RetryCount int32
	LastError  *string
}

func (q *Queries) MarkEmbeddingIndexFailed(ctx context.Context, arg MarkEmbeddingIndexFailedParams) error {
	_, err := q.db.Exec(ctx, markEmbeddingIndexFailed,
		arg.ObjectType,
		arg.ObjectID,
		arg.ModelID,
		arg.Status,
		arg.RetryCount,
		arg.LastError,
	)
	return err
}

const markEmbeddingIndexReady = `-- name: MarkEmbeddingIndexReady :exec
UPDATE embedding_index
SET status='ready', retry_count=0, last_error=NULL, updated_at=now()
WHERE object_type=$1 AND object_id=$2 AND model_id=$3
`

type MarkEmbeddingIndexReadyParams struct {
	ObjectType string
	ObjectID   uuid.UUID
	ModelID    uuid.UUID
}

func (q *Queries) MarkEmbeddingIndexReady(ctx context.Context, arg MarkEmbeddingIndexReadyParams) error {
	_, err := q.db.Exec(ctx, markEmbeddingIndexReady, arg.ObjectType, arg.ObjectID, arg.ModelID)
	return err
}

const updateKnowledgeArtifactEmbedding = `-- name: UpdateKnowledgeArtifactEmbedding :exec
UPDATE knowledge_artifacts SET embedding = $2, embedding_model_id = $3, updated_at = now()
WHERE id = $1
`

type UpdateKnowledgeArtifactEmbeddingParams struct {
	ID               uuid.UUID
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpdateKnowledgeArtifactEmbedding(ctx context.Context, arg UpdateKnowledgeArtifactEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateKnowledgeArtifactEmbedding, arg.ID, arg.Embedding, arg.EmbeddingModelID)
	return err
}

const updateSkillEmbedding = `-- name: UpdateSkillEmbedding :exec
UPDATE skills SET embedding = $2, embedding_model_id = $3, updated_at = now()
WHERE id = $1
`

type UpdateSkillEmbeddingParams struct {
	ID               uuid.UUID
	Embedding        *pgvector_go.Vector
	EmbeddingModelID *uuid.UUID
}

func (q *Queries) UpdateSkillEmbedding(ctx context.Context, arg UpdateSkillEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateSkillEmbedding, arg.ID, arg.Embedding, arg.EmbeddingModelID)
	return err
}
