// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scopes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (kind, external_id, name, parent_id, principal_id, meta, path)
VALUES ($1, $2, $3, $4, $5, $6, 'placeholder')
RETURNING id, kind, external_id, name, parent_id, principal_id, path::text, meta, created_at
`

type CreateScopeParams struct {
	Kind        string
	ExternalID  string
	Name        string
	ParentID    uuid.UUID
	PrincipalID uuid.UUID
	Meta        []byte
}

type CreateScopeRow struct {
	ID          uuid.UUID
	Kind        string
	ExternalID  string
	Name        string
	ParentID    uuid.UUID
	PrincipalID uuid.UUID
	Path        string
	Meta        []byte
	CreatedAt   time.Time
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (*CreateScopeRow, error) {
	row := q.db.QueryRow(ctx, createScope,
		arg.Kind,
		arg.ExternalID,
		arg.Name,
		arg.ParentID,
		arg.PrincipalID,
		arg.Meta,
	)
	var i CreateScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.CreatedAt,
	)
	return &i, err
}

const getAncestorScopeIDs = `-- name: GetAncestorScopeIDs :many
SELECT s2.id FROM scopes s1
JOIN scopes s2 ON s2.path @> s1.path
WHERE s1.id = $1
`

func (q *Queries) GetAncestorScopeIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAncestorScopeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeByExternalID = `-- name: GetScopeByExternalID :one
SELECT id, kind, external_id, name, parent_id, principal_id, path::text, meta, created_at
FROM scopes WHERE kind = $1 AND external_id = $2
`

type GetScopeByExternalIDParams struct {
	Kind       string
	ExternalID string
}

type GetScopeByExternalIDRow struct {
	ID          uuid.UUID
	Kind        string
	ExternalID  string
	Name        string
	ParentID    uuid.UUID
	PrincipalID uuid.UUID
	Path        string
	Meta        []byte
	CreatedAt   time.Time
}

func (q *Queries) GetScopeByExternalID(ctx context.Context, arg GetScopeByExternalIDParams) (*GetScopeByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getScopeByExternalID, arg.Kind, arg.ExternalID)
	var i GetScopeByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.CreatedAt,
	)
	return &i, err
}

const getScopeByID = `-- name: GetScopeByID :one
SELECT id, kind, external_id, name, parent_id, principal_id, path::text, meta, created_at
FROM scopes WHERE id = $1
`

type GetScopeByIDRow struct {
	ID          uuid.UUID
	Kind        string
	ExternalID  string
	Name        string
	ParentID    uuid.UUID
	PrincipalID uuid.UUID
	Path        string
	Meta        []byte
	CreatedAt   time.Time
}

func (q *Queries) GetScopeByID(ctx context.Context, id uuid.UUID) (*GetScopeByIDRow, error) {
	row := q.db.QueryRow(ctx, getScopeByID, id)
	var i GetScopeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.CreatedAt,
	)
	return &i, err
}
