// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scope_grants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScopeGrant = `-- name: CreateScopeGrant :one
INSERT INTO scope_grants (principal_id, scope_id, permissions, granted_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, principal_id, scope_id, permissions, granted_by, expires_at, created_at
`

type CreateScopeGrantParams struct {
	PrincipalID uuid.UUID
	ScopeID     uuid.UUID
	Permissions []string
	GrantedBy   *uuid.UUID
	ExpiresAt   *time.Time
}

func (q *Queries) CreateScopeGrant(ctx context.Context, arg CreateScopeGrantParams) (*ScopeGrant, error) {
	row := q.db.QueryRow(ctx, createScopeGrant,
		arg.PrincipalID,
		arg.ScopeID,
		arg.Permissions,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i ScopeGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.ScopeID,
		&i.Permissions,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredScopeGrants = `-- name: DeleteExpiredScopeGrants :exec
DELETE FROM scope_grants WHERE expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) DeleteExpiredScopeGrants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredScopeGrants)
	return err
}

const deleteScopeGrant = `-- name: DeleteScopeGrant :exec
DELETE FROM scope_grants WHERE id = $1
`

func (q *Queries) DeleteScopeGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScopeGrant, id)
	return err
}

const deleteScopeGrantByIDAndScope = `-- name: DeleteScopeGrantByIDAndScope :exec
DELETE FROM scope_grants WHERE id = $1 AND scope_id = $2
`

type DeleteScopeGrantByIDAndScopeParams struct {
	ID      uuid.UUID
	ScopeID uuid.UUID
}

func (q *Queries) DeleteScopeGrantByIDAndScope(ctx context.Context, arg DeleteScopeGrantByIDAndScopeParams) error {
	_, err := q.db.Exec(ctx, deleteScopeGrantByIDAndScope, arg.ID, arg.ScopeID)
	return err
}

const getScopeGrant = `-- name: GetScopeGrant :one
SELECT id, principal_id, scope_id, permissions, granted_by, expires_at, created_at
FROM scope_grants
WHERE principal_id = $1 AND scope_id = $2
`

type GetScopeGrantParams struct {
	PrincipalID uuid.UUID
	ScopeID     uuid.UUID
}

func (q *Queries) GetScopeGrant(ctx context.Context, arg GetScopeGrantParams) (*ScopeGrant, error) {
	row := q.db.QueryRow(ctx, getScopeGrant, arg.PrincipalID, arg.ScopeID)
	var i ScopeGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.ScopeID,
		&i.Permissions,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listScopeGrantsByPrincipal = `-- name: ListScopeGrantsByPrincipal :many
SELECT id, principal_id, scope_id, permissions, granted_by, expires_at, created_at
FROM scope_grants
WHERE principal_id = $1
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

func (q *Queries) ListScopeGrantsByPrincipal(ctx context.Context, principalID uuid.UUID) ([]*ScopeGrant, error) {
	rows, err := q.db.Query(ctx, listScopeGrantsByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScopeGrant{}
	for rows.Next() {
		var i ScopeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.ScopeID,
			&i.Permissions,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeGrantsByScope = `-- name: ListScopeGrantsByScope :many
SELECT id, principal_id, scope_id, permissions, granted_by, expires_at, created_at
FROM scope_grants
WHERE scope_id = $1
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

func (q *Queries) ListScopeGrantsByScope(ctx context.Context, scopeID uuid.UUID) ([]*ScopeGrant, error) {
	rows, err := q.db.Query(ctx, listScopeGrantsByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScopeGrant{}
	for rows.Next() {
		var i ScopeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.ScopeID,
			&i.Permissions,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScopeGrantPermissions = `-- name: UpdateScopeGrantPermissions :one
UPDATE scope_grants
SET permissions = $3
WHERE principal_id = $1 AND scope_id = $2
RETURNING id, principal_id, scope_id, permissions, granted_by, expires_at, created_at
`

type UpdateScopeGrantPermissionsParams struct {
	PrincipalID uuid.UUID
	ScopeID     uuid.UUID
	Permissions []string
}

func (q *Queries) UpdateScopeGrantPermissions(ctx context.Context, arg UpdateScopeGrantPermissionsParams) (*ScopeGrant, error) {
	row := q.db.QueryRow(ctx, updateScopeGrantPermissions, arg.PrincipalID, arg.ScopeID, arg.Permissions)
	var i ScopeGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.ScopeID,
		&i.Permissions,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}
