// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scopes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (kind, external_id, name, parent_id, principal_id, meta, path)
VALUES ($1, $2, $3, NULLIF($4, '00000000-0000-0000-0000-000000000000'::uuid), $5, $6, 'placeholder')
RETURNING id, kind, external_id, name, parent_id, principal_id, path::text, meta,
          repo_url, repo_default_branch, last_indexed_commit, created_at
`

type CreateScopeParams struct {
	Kind        string
	ExternalID  string
	Name        string
	Column4     interface{}
	PrincipalID uuid.UUID
	Meta        []byte
}

type CreateScopeRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (*CreateScopeRow, error) {
	row := q.db.QueryRow(ctx, createScope,
		arg.Kind,
		arg.ExternalID,
		arg.Name,
		arg.Column4,
		arg.PrincipalID,
		arg.Meta,
	)
	var i CreateScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.LastIndexedCommit,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteScope = `-- name: DeleteScope :exec
DELETE FROM scopes WHERE id = $1
`

func (q *Queries) DeleteScope(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScope, id)
	return err
}

const getAncestorScopeIDs = `-- name: GetAncestorScopeIDs :many
SELECT s2.id FROM scopes s1
JOIN scopes s2 ON s2.path @> s1.path
WHERE s1.id = $1
`

func (q *Queries) GetAncestorScopeIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAncestorScopeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeByExternalID = `-- name: GetScopeByExternalID :one
SELECT id, kind, external_id, name, parent_id, principal_id, path::text, meta,
       repo_url, repo_default_branch, last_indexed_commit, created_at
FROM scopes WHERE kind = $1 AND external_id = $2
`

type GetScopeByExternalIDParams struct {
	Kind       string
	ExternalID string
}

type GetScopeByExternalIDRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) GetScopeByExternalID(ctx context.Context, arg GetScopeByExternalIDParams) (*GetScopeByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getScopeByExternalID, arg.Kind, arg.ExternalID)
	var i GetScopeByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.LastIndexedCommit,
		&i.CreatedAt,
	)
	return &i, err
}

const getScopeByID = `-- name: GetScopeByID :one
SELECT id, kind, external_id, name, parent_id, principal_id, path::text, meta,
       repo_url, repo_default_branch, last_indexed_commit, created_at
FROM scopes WHERE id = $1
`

type GetScopeByIDRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) GetScopeByID(ctx context.Context, id uuid.UUID) (*GetScopeByIDRow, error) {
	row := q.db.QueryRow(ctx, getScopeByID, id)
	var i GetScopeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.LastIndexedCommit,
		&i.CreatedAt,
	)
	return &i, err
}

const listScopes = `-- name: ListScopes :many
SELECT id, kind, external_id, name, parent_id, principal_id, path::text, meta,
       repo_url, repo_default_branch, last_indexed_commit, created_at
FROM scopes
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListScopesParams struct {
	Limit  int32
	Offset int32
}

type ListScopesRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) ListScopes(ctx context.Context, arg ListScopesParams) ([]*ListScopesRow, error) {
	rows, err := q.db.Query(ctx, listScopes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListScopesRow{}
	for rows.Next() {
		var i ListScopesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ExternalID,
			&i.Name,
			&i.ParentID,
			&i.PrincipalID,
			&i.Path,
			&i.Meta,
			&i.RepoUrl,
			&i.RepoDefaultBranch,
			&i.LastIndexedCommit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastIndexedCommit = `-- name: SetLastIndexedCommit :exec
UPDATE scopes SET last_indexed_commit = $2 WHERE id = $1
`

type SetLastIndexedCommitParams struct {
	ID                uuid.UUID
	LastIndexedCommit *string
}

func (q *Queries) SetLastIndexedCommit(ctx context.Context, arg SetLastIndexedCommitParams) error {
	_, err := q.db.Exec(ctx, setLastIndexedCommit, arg.ID, arg.LastIndexedCommit)
	return err
}

const setScopeRepo = `-- name: SetScopeRepo :one
UPDATE scopes
SET repo_url = $2, repo_default_branch = $3
WHERE id = $1 AND kind = 'project'
RETURNING id, kind, external_id, name, parent_id, principal_id, path::text, meta,
          repo_url, repo_default_branch, last_indexed_commit, created_at
`

type SetScopeRepoParams struct {
	ID                uuid.UUID
	RepoUrl           *string
	RepoDefaultBranch string
}

type SetScopeRepoRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) SetScopeRepo(ctx context.Context, arg SetScopeRepoParams) (*SetScopeRepoRow, error) {
	row := q.db.QueryRow(ctx, setScopeRepo, arg.ID, arg.RepoUrl, arg.RepoDefaultBranch)
	var i SetScopeRepoRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.LastIndexedCommit,
		&i.CreatedAt,
	)
	return &i, err
}

const updateScope = `-- name: UpdateScope :one
UPDATE scopes SET name = $2, meta = $3 WHERE id = $1
RETURNING id, kind, external_id, name, parent_id, principal_id, path::text, meta,
          repo_url, repo_default_branch, last_indexed_commit, created_at
`

type UpdateScopeParams struct {
	ID   uuid.UUID
	Name string
	Meta []byte
}

type UpdateScopeRow struct {
	ID                uuid.UUID
	Kind              string
	ExternalID        string
	Name              string
	ParentID          *uuid.UUID
	PrincipalID       uuid.UUID
	Path              string
	Meta              []byte
	RepoUrl           *string
	RepoDefaultBranch string
	LastIndexedCommit *string
	CreatedAt         time.Time
}

func (q *Queries) UpdateScope(ctx context.Context, arg UpdateScopeParams) (*UpdateScopeRow, error) {
	row := q.db.QueryRow(ctx, updateScope, arg.ID, arg.Name, arg.Meta)
	var i UpdateScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.ParentID,
		&i.PrincipalID,
		&i.Path,
		&i.Meta,
		&i.RepoUrl,
		&i.RepoDefaultBranch,
		&i.LastIndexedCommit,
		&i.CreatedAt,
	)
	return &i, err
}
