// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (scope_id, principal_id, meta)
VALUES ($1, $2, $3)
RETURNING id, scope_id, principal_id, started_at, ended_at, meta
`

type CreateSessionParams struct {
	ScopeID     uuid.UUID
	PrincipalID uuid.UUID
	Meta        []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ScopeID, arg.PrincipalID, arg.Meta)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.PrincipalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Meta,
	)
	return &i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET ended_at = COALESCE($2::timestamptz, now()),
    meta     = CASE WHEN $3::jsonb IS NOT NULL THEN $3 ELSE meta END
WHERE id = $1
RETURNING id, scope_id, principal_id, started_at, ended_at, meta
`

type EndSessionParams struct {
	ID      uuid.UUID
	Column2 time.Time
	Column3 []byte
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.ID, arg.Column2, arg.Column3)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.PrincipalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Meta,
	)
	return &i, err
}

const getSession = `-- name: GetSession :one
SELECT id, scope_id, principal_id, started_at, ended_at, meta
FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (*Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.PrincipalID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Meta,
	)
	return &i, err
}
