// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sharing_grants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSharingGrant = `-- name: CreateSharingGrant :one
INSERT INTO sharing_grants (memory_id, artifact_id, grantee_scope_id, granted_by, can_reshare, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, memory_id, artifact_id, grantee_scope_id, granted_by, can_reshare, expires_at, created_at
`

type CreateSharingGrantParams struct {
	MemoryID       *uuid.UUID
	ArtifactID     *uuid.UUID
	GranteeScopeID uuid.UUID
	GrantedBy      uuid.UUID
	CanReshare     bool
	ExpiresAt      *time.Time
}

func (q *Queries) CreateSharingGrant(ctx context.Context, arg CreateSharingGrantParams) (*SharingGrant, error) {
	row := q.db.QueryRow(ctx, createSharingGrant,
		arg.MemoryID,
		arg.ArtifactID,
		arg.GranteeScopeID,
		arg.GrantedBy,
		arg.CanReshare,
		arg.ExpiresAt,
	)
	var i SharingGrant
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.ArtifactID,
		&i.GranteeScopeID,
		&i.GrantedBy,
		&i.CanReshare,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const isArtifactGranted = `-- name: IsArtifactGranted :one
SELECT EXISTS (
    SELECT 1 FROM sharing_grants
    WHERE artifact_id = $1
      AND grantee_scope_id = $2
      AND (expires_at IS NULL OR expires_at > now())
)
`

type IsArtifactGrantedParams struct {
	ArtifactID     *uuid.UUID
	GranteeScopeID uuid.UUID
}

func (q *Queries) IsArtifactGranted(ctx context.Context, arg IsArtifactGrantedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isArtifactGranted, arg.ArtifactID, arg.GranteeScopeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMemoryGranted = `-- name: IsMemoryGranted :one
SELECT EXISTS (
    SELECT 1 FROM sharing_grants
    WHERE memory_id = $1
      AND grantee_scope_id = $2
      AND (expires_at IS NULL OR expires_at > now())
)
`

type IsMemoryGrantedParams struct {
	MemoryID       *uuid.UUID
	GranteeScopeID uuid.UUID
}

func (q *Queries) IsMemoryGranted(ctx context.Context, arg IsMemoryGrantedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemoryGranted, arg.MemoryID, arg.GranteeScopeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSharingGrants = `-- name: ListSharingGrants :many
SELECT id, memory_id, artifact_id, grantee_scope_id, granted_by, can_reshare, expires_at, created_at
FROM sharing_grants WHERE grantee_scope_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSharingGrantsParams struct {
	GranteeScopeID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListSharingGrants(ctx context.Context, arg ListSharingGrantsParams) ([]*SharingGrant, error) {
	rows, err := q.db.Query(ctx, listSharingGrants, arg.GranteeScopeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SharingGrant{}
	for rows.Next() {
		var i SharingGrant
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.ArtifactID,
			&i.GranteeScopeID,
			&i.GrantedBy,
			&i.CanReshare,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSharingGrant = `-- name: RevokeSharingGrant :exec
DELETE FROM sharing_grants WHERE id = $1
`

func (q *Queries) RevokeSharingGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSharingGrant, id)
	return err
}
