// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countSkillEndorsements = `-- name: CountSkillEndorsements :one
SELECT COUNT(*) FROM skill_endorsements WHERE skill_id = $1
`

func (q *Queries) CountSkillEndorsements(ctx context.Context, skillID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSkillEndorsements, skillID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills
(scope_id, author_id, source_artifact_id, slug, name, description,
 agent_types, body, parameters, visibility, status, published_at,
 deprecated_at, review_required, version, previous_version,
 embedding, embedding_model_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
RETURNING id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at
`

type CreateSkillParams struct {
	ScopeID          uuid.UUID
	AuthorID         uuid.UUID
	SourceArtifactID uuid.UUID
	Slug             string
	Name             string
	Description      string
	AgentTypes       []string
	Body             string
	Parameters       []byte
	Visibility       string
	Status           string
	PublishedAt      time.Time
	DeprecatedAt     time.Time
	ReviewRequired   int32
	Version          int32
	PreviousVersion  uuid.UUID
	Embedding        pgvector_go.Vector
	EmbeddingModelID uuid.UUID
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (*Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ScopeID,
		arg.AuthorID,
		arg.SourceArtifactID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.AgentTypes,
		arg.Body,
		arg.Parameters,
		arg.Visibility,
		arg.Status,
		arg.PublishedAt,
		arg.DeprecatedAt,
		arg.ReviewRequired,
		arg.Version,
		arg.PreviousVersion,
		arg.Embedding,
		arg.EmbeddingModelID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.AuthorID,
		&i.SourceArtifactID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AgentTypes,
		&i.Body,
		&i.Parameters,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Version,
		&i.PreviousVersion,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.InvocationCount,
		&i.LastInvokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createSkillEndorsement = `-- name: CreateSkillEndorsement :one
INSERT INTO skill_endorsements (skill_id, endorser_id, note)
VALUES ($1,$2,$3)
RETURNING id, skill_id, endorser_id, note, created_at
`

type CreateSkillEndorsementParams struct {
	SkillID    uuid.UUID
	EndorserID uuid.UUID
	Note       *string
}

func (q *Queries) CreateSkillEndorsement(ctx context.Context, arg CreateSkillEndorsementParams) (*SkillEndorsement, error) {
	row := q.db.QueryRow(ctx, createSkillEndorsement, arg.SkillID, arg.EndorserID, arg.Note)
	var i SkillEndorsement
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.EndorserID,
		&i.Note,
		&i.CreatedAt,
	)
	return &i, err
}

const getSkill = `-- name: GetSkill :one
SELECT id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at
FROM skills WHERE id = $1
`

func (q *Queries) GetSkill(ctx context.Context, id uuid.UUID) (*Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.AuthorID,
		&i.SourceArtifactID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AgentTypes,
		&i.Body,
		&i.Parameters,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Version,
		&i.PreviousVersion,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.InvocationCount,
		&i.LastInvokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSkillBySlug = `-- name: GetSkillBySlug :one
SELECT id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at
FROM skills WHERE scope_id = $1 AND slug = $2
`

type GetSkillBySlugParams struct {
	ScopeID uuid.UUID
	Slug    string
}

func (q *Queries) GetSkillBySlug(ctx context.Context, arg GetSkillBySlugParams) (*Skill, error) {
	row := q.db.QueryRow(ctx, getSkillBySlug, arg.ScopeID, arg.Slug)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.AuthorID,
		&i.SourceArtifactID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AgentTypes,
		&i.Body,
		&i.Parameters,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Version,
		&i.PreviousVersion,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.InvocationCount,
		&i.LastInvokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSkillEndorsementByEndorser = `-- name: GetSkillEndorsementByEndorser :one
SELECT id, skill_id, endorser_id, note, created_at
FROM skill_endorsements WHERE skill_id=$1 AND endorser_id=$2
`

type GetSkillEndorsementByEndorserParams struct {
	SkillID    uuid.UUID
	EndorserID uuid.UUID
}

func (q *Queries) GetSkillEndorsementByEndorser(ctx context.Context, arg GetSkillEndorsementByEndorserParams) (*SkillEndorsement, error) {
	row := q.db.QueryRow(ctx, getSkillEndorsementByEndorser, arg.SkillID, arg.EndorserID)
	var i SkillEndorsement
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.EndorserID,
		&i.Note,
		&i.CreatedAt,
	)
	return &i, err
}

const listPublishedSkillsForAgent = `-- name: ListPublishedSkillsForAgent :many
SELECT id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at
FROM skills
WHERE status = 'published'
  AND scope_id = ANY($1::uuid[])
  AND ($2 = 'any' OR 'any' = ANY(agent_types) OR $2 = ANY(agent_types))
ORDER BY created_at DESC
`

type ListPublishedSkillsForAgentParams struct {
	Column1 []uuid.UUID
	Column2 interface{}
}

func (q *Queries) ListPublishedSkillsForAgent(ctx context.Context, arg ListPublishedSkillsForAgentParams) ([]*Skill, error) {
	rows, err := q.db.Query(ctx, listPublishedSkillsForAgent, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.AuthorID,
			&i.SourceArtifactID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AgentTypes,
			&i.Body,
			&i.Parameters,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Version,
			&i.PreviousVersion,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.InvocationCount,
			&i.LastInvokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallSkillsByFTS = `-- name: RecallSkillsByFTS :many
SELECT id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at,
    ts_rank_cd(to_tsvector('postbrain_fts', description || ' ' || body),
               plainto_tsquery('postbrain_fts', $1)) AS score
FROM skills
WHERE status = 'published'
  AND scope_id = ANY($2::uuid[])
  AND ($3 = 'any' OR 'any' = ANY(agent_types) OR $3 = ANY(agent_types))
  AND to_tsvector('postbrain_fts', description || ' ' || body)
      @@ plainto_tsquery('postbrain_fts', $1)
ORDER BY score DESC
LIMIT $4
`

type RecallSkillsByFTSParams struct {
	PlaintoTsquery string
	Column2        []uuid.UUID
	Column3        interface{}
	Limit          int32
}

type RecallSkillsByFTSRow struct {
	ID               uuid.UUID
	ScopeID          uuid.UUID
	AuthorID         uuid.UUID
	SourceArtifactID uuid.UUID
	Slug             string
	Name             string
	Description      string
	AgentTypes       []string
	Body             string
	Parameters       []byte
	Visibility       string
	Status           string
	PublishedAt      time.Time
	DeprecatedAt     time.Time
	ReviewRequired   int32
	Version          int32
	PreviousVersion  uuid.UUID
	Embedding        pgvector_go.Vector
	EmbeddingModelID uuid.UUID
	InvocationCount  int32
	LastInvokedAt    time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Score            float32
}

func (q *Queries) RecallSkillsByFTS(ctx context.Context, arg RecallSkillsByFTSParams) ([]*RecallSkillsByFTSRow, error) {
	rows, err := q.db.Query(ctx, recallSkillsByFTS,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallSkillsByFTSRow{}
	for rows.Next() {
		var i RecallSkillsByFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.AuthorID,
			&i.SourceArtifactID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AgentTypes,
			&i.Body,
			&i.Parameters,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Version,
			&i.PreviousVersion,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.InvocationCount,
			&i.LastInvokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallSkillsByVector = `-- name: RecallSkillsByVector :many
SELECT id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at,
    (embedding <=> $1) AS score
FROM skills
WHERE status = 'published'
  AND scope_id = ANY($2::uuid[])
  AND ($3 = 'any' OR 'any' = ANY(agent_types) OR $3 = ANY(agent_types))
ORDER BY embedding <=> $1
LIMIT $4
`

type RecallSkillsByVectorParams struct {
	Embedding pgvector_go.Vector
	Column2   []uuid.UUID
	Column3   interface{}
	Limit     int32
}

type RecallSkillsByVectorRow struct {
	ID               uuid.UUID
	ScopeID          uuid.UUID
	AuthorID         uuid.UUID
	SourceArtifactID uuid.UUID
	Slug             string
	Name             string
	Description      string
	AgentTypes       []string
	Body             string
	Parameters       []byte
	Visibility       string
	Status           string
	PublishedAt      time.Time
	DeprecatedAt     time.Time
	ReviewRequired   int32
	Version          int32
	PreviousVersion  uuid.UUID
	Embedding        pgvector_go.Vector
	EmbeddingModelID uuid.UUID
	InvocationCount  int32
	LastInvokedAt    time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Score            interface{}
}

func (q *Queries) RecallSkillsByVector(ctx context.Context, arg RecallSkillsByVectorParams) ([]*RecallSkillsByVectorRow, error) {
	rows, err := q.db.Query(ctx, recallSkillsByVector,
		arg.Embedding,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RecallSkillsByVectorRow{}
	for rows.Next() {
		var i RecallSkillsByVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.AuthorID,
			&i.SourceArtifactID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AgentTypes,
			&i.Body,
			&i.Parameters,
			&i.Visibility,
			&i.Status,
			&i.PublishedAt,
			&i.DeprecatedAt,
			&i.ReviewRequired,
			&i.Version,
			&i.PreviousVersion,
			&i.Embedding,
			&i.EmbeddingModelID,
			&i.InvocationCount,
			&i.LastInvokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotSkillVersion = `-- name: SnapshotSkillVersion :exec
INSERT INTO skill_history (skill_id, version, body, parameters, changed_by, change_note)
VALUES ($1,$2,$3,$4,$5,$6)
`

type SnapshotSkillVersionParams struct {
	SkillID    uuid.UUID
	Version    int32
	Body       string
	Parameters []byte
	ChangedBy  uuid.UUID
	ChangeNote *string
}

func (q *Queries) SnapshotSkillVersion(ctx context.Context, arg SnapshotSkillVersionParams) error {
	_, err := q.db.Exec(ctx, snapshotSkillVersion,
		arg.SkillID,
		arg.Version,
		arg.Body,
		arg.Parameters,
		arg.ChangedBy,
		arg.ChangeNote,
	)
	return err
}

const updateSkillContent = `-- name: UpdateSkillContent :one
UPDATE skills
SET body=$2, parameters=$3, embedding=$4, embedding_model_id=$5,
    version=version+1, updated_at=now()
WHERE id=$1
RETURNING id, scope_id, author_id, source_artifact_id,
    slug, name, description, agent_types, body, parameters,
    visibility, status, published_at, deprecated_at, review_required,
    version, previous_version, embedding, embedding_model_id,
    invocation_count, last_invoked_at, created_at, updated_at
`

type UpdateSkillContentParams struct {
	ID               uuid.UUID
	Body             string
	Parameters       []byte
	Embedding        pgvector_go.Vector
	EmbeddingModelID uuid.UUID
}

func (q *Queries) UpdateSkillContent(ctx context.Context, arg UpdateSkillContentParams) (*Skill, error) {
	row := q.db.QueryRow(ctx, updateSkillContent,
		arg.ID,
		arg.Body,
		arg.Parameters,
		arg.Embedding,
		arg.EmbeddingModelID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.AuthorID,
		&i.SourceArtifactID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AgentTypes,
		&i.Body,
		&i.Parameters,
		&i.Visibility,
		&i.Status,
		&i.PublishedAt,
		&i.DeprecatedAt,
		&i.ReviewRequired,
		&i.Version,
		&i.PreviousVersion,
		&i.Embedding,
		&i.EmbeddingModelID,
		&i.InvocationCount,
		&i.LastInvokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateSkillStatus = `-- name: UpdateSkillStatus :exec
UPDATE skills SET status=$2, published_at=$3, deprecated_at=$4, updated_at=now()
WHERE id=$1
`

type UpdateSkillStatusParams struct {
	ID           uuid.UUID
	Status       string
	PublishedAt  time.Time
	DeprecatedAt time.Time
}

func (q *Queries) UpdateSkillStatus(ctx context.Context, arg UpdateSkillStatusParams) error {
	_, err := q.db.Exec(ctx, updateSkillStatus,
		arg.ID,
		arg.Status,
		arg.PublishedAt,
		arg.DeprecatedAt,
	)
	return err
}
