// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAllSkillFiles = `-- name: DeleteAllSkillFiles :exec
DELETE FROM skill_files
WHERE skill_id = $1
`

func (q *Queries) DeleteAllSkillFiles(ctx context.Context, skillID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSkillFiles, skillID)
	return err
}

const deleteSkillFile = `-- name: DeleteSkillFile :exec
DELETE FROM skill_files
WHERE skill_id = $1 AND relative_path = $2
`

type DeleteSkillFileParams struct {
	SkillID      uuid.UUID
	RelativePath string
}

func (q *Queries) DeleteSkillFile(ctx context.Context, arg DeleteSkillFileParams) error {
	_, err := q.db.Exec(ctx, deleteSkillFile, arg.SkillID, arg.RelativePath)
	return err
}

const getSkillFile = `-- name: GetSkillFile :one
SELECT id, skill_id, relative_path, content, is_executable, created_at, updated_at
FROM skill_files
WHERE skill_id = $1 AND relative_path = $2
`

type GetSkillFileParams struct {
	SkillID      uuid.UUID
	RelativePath string
}

func (q *Queries) GetSkillFile(ctx context.Context, arg GetSkillFileParams) (*SkillFile, error) {
	row := q.db.QueryRow(ctx, getSkillFile, arg.SkillID, arg.RelativePath)
	var i SkillFile
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.RelativePath,
		&i.Content,
		&i.IsExecutable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listSkillFiles = `-- name: ListSkillFiles :many
SELECT id, skill_id, relative_path, content, is_executable, created_at, updated_at
FROM skill_files
WHERE skill_id = $1
ORDER BY relative_path
`

func (q *Queries) ListSkillFiles(ctx context.Context, skillID uuid.UUID) ([]*SkillFile, error) {
	rows, err := q.db.Query(ctx, listSkillFiles, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SkillFile{}
	for rows.Next() {
		var i SkillFile
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.RelativePath,
			&i.Content,
			&i.IsExecutable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillHistoryFiles = `-- name: ListSkillHistoryFiles :many
SELECT id, skill_id, version, relative_path, content, is_executable, created_at
FROM skill_history_files
WHERE skill_id = $1 AND version = $2
ORDER BY relative_path
`

type ListSkillHistoryFilesParams struct {
	SkillID uuid.UUID
	Version int32
}

func (q *Queries) ListSkillHistoryFiles(ctx context.Context, arg ListSkillHistoryFilesParams) ([]*SkillHistoryFile, error) {
	rows, err := q.db.Query(ctx, listSkillHistoryFiles, arg.SkillID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SkillHistoryFile{}
	for rows.Next() {
		var i SkillHistoryFile
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Version,
			&i.RelativePath,
			&i.Content,
			&i.IsExecutable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotSkillFiles = `-- name: SnapshotSkillFiles :exec
INSERT INTO skill_history_files (skill_id, version, relative_path, content, is_executable)
SELECT sf.skill_id, $2, sf.relative_path, sf.content, sf.is_executable
FROM skill_files sf
WHERE sf.skill_id = $1
ON CONFLICT (skill_id, version, relative_path) DO NOTHING
`

type SnapshotSkillFilesParams struct {
	SkillID uuid.UUID
	Version int32
}

func (q *Queries) SnapshotSkillFiles(ctx context.Context, arg SnapshotSkillFilesParams) error {
	_, err := q.db.Exec(ctx, snapshotSkillFiles, arg.SkillID, arg.Version)
	return err
}

const upsertSkillFile = `-- name: UpsertSkillFile :one
INSERT INTO skill_files (skill_id, relative_path, content, is_executable)
VALUES ($1, $2, $3, $4)
ON CONFLICT (skill_id, relative_path)
DO UPDATE SET
    content       = EXCLUDED.content,
    is_executable = EXCLUDED.is_executable,
    updated_at    = now()
RETURNING id, skill_id, relative_path, content, is_executable, created_at, updated_at
`

type UpsertSkillFileParams struct {
	SkillID      uuid.UUID
	RelativePath string
	Content      string
	IsExecutable bool
}

func (q *Queries) UpsertSkillFile(ctx context.Context, arg UpsertSkillFileParams) (*SkillFile, error) {
	row := q.db.QueryRow(ctx, upsertSkillFile,
		arg.SkillID,
		arg.RelativePath,
		arg.Content,
		arg.IsExecutable,
	)
	var i SkillFile
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.RelativePath,
		&i.Content,
		&i.IsExecutable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
