// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findPrincipalBySocialIdentity = `-- name: FindPrincipalBySocialIdentity :one
SELECT principal_id
FROM social_identities
WHERE provider = $1
  AND provider_id = $2
`

type FindPrincipalBySocialIdentityParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) FindPrincipalBySocialIdentity(ctx context.Context, arg FindPrincipalBySocialIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findPrincipalBySocialIdentity, arg.Provider, arg.ProviderID)
	var principal_id uuid.UUID
	err := row.Scan(&principal_id)
	return principal_id, err
}

const upsertSocialIdentity = `-- name: UpsertSocialIdentity :one
INSERT INTO social_identities (
    principal_id,
    provider,
    provider_id,
    email,
    display_name,
    avatar_url,
    raw_profile
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, provider_id)
DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    raw_profile = EXCLUDED.raw_profile,
    updated_at = now()
RETURNING id, principal_id, provider, provider_id, email, display_name, avatar_url, raw_profile, created_at, updated_at
`

type UpsertSocialIdentityParams struct {
	PrincipalID uuid.UUID
	Provider    string
	ProviderID  string
	Email       *string
	DisplayName *string
	AvatarUrl   *string
	RawProfile  []byte
}

func (q *Queries) UpsertSocialIdentity(ctx context.Context, arg UpsertSocialIdentityParams) (*SocialIdentity, error) {
	row := q.db.QueryRow(ctx, upsertSocialIdentity,
		arg.PrincipalID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.RawProfile,
	)
	var i SocialIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
