// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staleness.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const hasOpenStalenessFlag = `-- name: HasOpenStalenessFlag :one
SELECT EXISTS(
    SELECT 1 FROM staleness_flags
    WHERE artifact_id=$1 AND signal=$2 AND status='open'
)
`

type HasOpenStalenessFlagParams struct {
	ArtifactID uuid.UUID
	Signal     string
}

func (q *Queries) HasOpenStalenessFlag(ctx context.Context, arg HasOpenStalenessFlagParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenStalenessFlag, arg.ArtifactID, arg.Signal)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertStalenessFlag = `-- name: InsertStalenessFlag :one
INSERT INTO staleness_flags (artifact_id, signal, confidence, evidence, status)
VALUES ($1,$2,$3,$4,COALESCE($5,'open'))
RETURNING id, artifact_id, signal, confidence, evidence, status, flagged_at,
          reviewed_by, reviewed_at, review_note
`

type InsertStalenessFlagParams struct {
	ArtifactID uuid.UUID
	Signal     string
	Confidence float64
	Evidence   []byte
	Column5    interface{}
}

func (q *Queries) InsertStalenessFlag(ctx context.Context, arg InsertStalenessFlagParams) (*StalenessFlag, error) {
	row := q.db.QueryRow(ctx, insertStalenessFlag,
		arg.ArtifactID,
		arg.Signal,
		arg.Confidence,
		arg.Evidence,
		arg.Column5,
	)
	var i StalenessFlag
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Signal,
		&i.Confidence,
		&i.Evidence,
		&i.Status,
		&i.FlaggedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
	)
	return &i, err
}

const listStalenessFlags = `-- name: ListStalenessFlags :many
SELECT id, artifact_id, signal, confidence, evidence, status, flagged_at,
       reviewed_by, reviewed_at, review_note
FROM staleness_flags
WHERE ($1='' OR status=$1)
ORDER BY flagged_at DESC
LIMIT $2 OFFSET $3
`

type ListStalenessFlagsParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListStalenessFlags(ctx context.Context, arg ListStalenessFlagsParams) ([]*StalenessFlag, error) {
	rows, err := q.db.Query(ctx, listStalenessFlags, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*StalenessFlag{}
	for rows.Next() {
		var i StalenessFlag
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Signal,
			&i.Confidence,
			&i.Evidence,
			&i.Status,
			&i.FlaggedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStalenessFlag = `-- name: UpdateStalenessFlag :exec
UPDATE staleness_flags
SET status=$2, reviewed_by=$3, review_note=$4, reviewed_at=now()
WHERE id=$1
`

type UpdateStalenessFlagParams struct {
	ID         uuid.UUID
	Status     string
	ReviewedBy uuid.UUID
	ReviewNote *string
}

func (q *Queries) UpdateStalenessFlag(ctx context.Context, arg UpdateStalenessFlagParams) error {
	_, err := q.db.Exec(ctx, updateStalenessFlag,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNote,
	)
	return err
}
