// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (principal_id, token_hash, name, scope_ids, permissions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, principal_id, token_hash, name, scope_ids, permissions, expires_at, last_used_at, created_at, revoked_at
`

type CreateTokenParams struct {
	PrincipalID uuid.UUID
	TokenHash   string
	Name        string
	ScopeIds    []uuid.UUID
	Permissions []string
	ExpiresAt   *time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (*Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.PrincipalID,
		arg.TokenHash,
		arg.Name,
		arg.ScopeIds,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.Name,
		&i.ScopeIds,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, principal_id, token_hash, name, scope_ids, permissions, expires_at, last_used_at, created_at, revoked_at
FROM tokens
ORDER BY created_at DESC
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]*Token, error) {
	rows, err := q.db.Query(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.TokenHash,
			&i.Name,
			&i.ScopeIds,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByPrincipal = `-- name: ListTokensByPrincipal :many
SELECT id, principal_id, token_hash, name, scope_ids, permissions, expires_at, last_used_at, created_at, revoked_at
FROM tokens
WHERE principal_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByPrincipal(ctx context.Context, principalID uuid.UUID) ([]*Token, error) {
	rows, err := q.db.Query(ctx, listTokensByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.TokenHash,
			&i.Name,
			&i.ScopeIds,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupToken = `-- name: LookupToken :one
SELECT id, principal_id, token_hash, name, scope_ids, permissions, expires_at, last_used_at, created_at, revoked_at
FROM tokens WHERE token_hash = $1
`

func (q *Queries) LookupToken(ctx context.Context, tokenHash string) (*Token, error) {
	row := q.db.QueryRow(ctx, lookupToken, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.Name,
		&i.ScopeIds,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeToken, id)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
